'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por herramienta.
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     el código se vuelve a generar. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class OpenAuthProviders
    
    '''<summary>
    '''Control providersList.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents providersList As Global.System.Web.UI.WebControls.ListView
    
End Class
