//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KB2C.Data.ServiceOrdenes {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kallsony.com/util/falta")]
    public partial class Falta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idErrorField;
        
        private bool idErrorFieldSpecified;
        
        private string nombreErrorField;
        
        private string descripcionErrorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long idError {
            get {
                return this.idErrorField;
            }
            set {
                this.idErrorField = value;
                this.RaisePropertyChanged("idError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idErrorSpecified {
            get {
                return this.idErrorFieldSpecified;
            }
            set {
                this.idErrorFieldSpecified = value;
                this.RaisePropertyChanged("idErrorSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string nombreError {
            get {
                return this.nombreErrorField;
            }
            set {
                this.nombreErrorField = value;
                this.RaisePropertyChanged("nombreError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string descripcionError {
            get {
                return this.descripcionErrorField;
            }
            set {
                this.descripcionErrorField = value;
                this.RaisePropertyChanged("descripcionError");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kallsony.com/entidad/producto")]
    public partial class Tipo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idTipoField;
        
        private bool idTipoFieldSpecified;
        
        private string nombreTipoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idTipo {
            get {
                return this.idTipoField;
            }
            set {
                this.idTipoField = value;
                this.RaisePropertyChanged("idTipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idTipoSpecified {
            get {
                return this.idTipoFieldSpecified;
            }
            set {
                this.idTipoFieldSpecified = value;
                this.RaisePropertyChanged("idTipoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombreTipo {
            get {
                return this.nombreTipoField;
            }
            set {
                this.nombreTipoField = value;
                this.RaisePropertyChanged("nombreTipo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kallsony.com/entidad/producto")]
    public partial class TipoProducto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Tipo categoriaField;
        
        private Tipo subCategoriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Tipo categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
                this.RaisePropertyChanged("categoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Tipo subCategoria {
            get {
                return this.subCategoriaField;
            }
            set {
                this.subCategoriaField = value;
                this.RaisePropertyChanged("subCategoria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kallsony.com/entidad/producto")]
    public partial class Producto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idProductoField;
        
        private bool idProductoFieldSpecified;
        
        private string codigoProductoField;
        
        private string nombreProductoField;
        
        private string descripcionProductoField;
        
        private string fabricanteProductoField;
        
        private string nombreImagenProductoField;
        
        private float precioProductoField;
        
        private bool precioProductoFieldSpecified;
        
        private TipoProducto tipoProductoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long idProducto {
            get {
                return this.idProductoField;
            }
            set {
                this.idProductoField = value;
                this.RaisePropertyChanged("idProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idProductoSpecified {
            get {
                return this.idProductoFieldSpecified;
            }
            set {
                this.idProductoFieldSpecified = value;
                this.RaisePropertyChanged("idProductoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigoProducto {
            get {
                return this.codigoProductoField;
            }
            set {
                this.codigoProductoField = value;
                this.RaisePropertyChanged("codigoProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombreProducto {
            get {
                return this.nombreProductoField;
            }
            set {
                this.nombreProductoField = value;
                this.RaisePropertyChanged("nombreProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string descripcionProducto {
            get {
                return this.descripcionProductoField;
            }
            set {
                this.descripcionProductoField = value;
                this.RaisePropertyChanged("descripcionProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string fabricanteProducto {
            get {
                return this.fabricanteProductoField;
            }
            set {
                this.fabricanteProductoField = value;
                this.RaisePropertyChanged("fabricanteProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombreImagenProducto {
            get {
                return this.nombreImagenProductoField;
            }
            set {
                this.nombreImagenProductoField = value;
                this.RaisePropertyChanged("nombreImagenProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public float precioProducto {
            get {
                return this.precioProductoField;
            }
            set {
                this.precioProductoField = value;
                this.RaisePropertyChanged("precioProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool precioProductoSpecified {
            get {
                return this.precioProductoFieldSpecified;
            }
            set {
                this.precioProductoFieldSpecified = value;
                this.RaisePropertyChanged("precioProductoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public TipoProducto tipoProducto {
            get {
                return this.tipoProductoField;
            }
            set {
                this.tipoProductoField = value;
                this.RaisePropertyChanged("tipoProducto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kallsony.com/entidad/orden")]
    public partial class Item : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cantidadField;
        
        private bool tipoField;
        
        private int idCampaniaField;
        
        private bool idCampaniaFieldSpecified;
        
        private Producto productoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idCampania {
            get {
                return this.idCampaniaField;
            }
            set {
                this.idCampaniaField = value;
                this.RaisePropertyChanged("idCampania");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idCampaniaSpecified {
            get {
                return this.idCampaniaFieldSpecified;
            }
            set {
                this.idCampaniaFieldSpecified = value;
                this.RaisePropertyChanged("idCampaniaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public Producto producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
                this.RaisePropertyChanged("producto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kallsony.com/entidad/orden")]
    public partial class Orden : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idOrdenField;
        
        private bool idOrdenFieldSpecified;
        
        private int idPreOrdenField;
        
        private bool idPreOrdenFieldSpecified;
        
        private System.DateTime fechaOrdenField;
        
        private bool fechaOrdenFieldSpecified;
        
        private string estadoOrdenField;
        
        private int idEstadoOrdenField;
        
        private bool idEstadoOrdenFieldSpecified;
        
        private int numeroItemsField;
        
        private bool numeroItemsFieldSpecified;
        
        private double totalField;
        
        private bool totalFieldSpecified;
        
        private Usuario clienteField;
        
        private Item[] listaItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idOrden {
            get {
                return this.idOrdenField;
            }
            set {
                this.idOrdenField = value;
                this.RaisePropertyChanged("idOrden");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idOrdenSpecified {
            get {
                return this.idOrdenFieldSpecified;
            }
            set {
                this.idOrdenFieldSpecified = value;
                this.RaisePropertyChanged("idOrdenSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idPreOrden {
            get {
                return this.idPreOrdenField;
            }
            set {
                this.idPreOrdenField = value;
                this.RaisePropertyChanged("idPreOrden");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idPreOrdenSpecified {
            get {
                return this.idPreOrdenFieldSpecified;
            }
            set {
                this.idPreOrdenFieldSpecified = value;
                this.RaisePropertyChanged("idPreOrdenSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaOrden {
            get {
                return this.fechaOrdenField;
            }
            set {
                this.fechaOrdenField = value;
                this.RaisePropertyChanged("fechaOrden");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaOrdenSpecified {
            get {
                return this.fechaOrdenFieldSpecified;
            }
            set {
                this.fechaOrdenFieldSpecified = value;
                this.RaisePropertyChanged("fechaOrdenSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string estadoOrden {
            get {
                return this.estadoOrdenField;
            }
            set {
                this.estadoOrdenField = value;
                this.RaisePropertyChanged("estadoOrden");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idEstadoOrden {
            get {
                return this.idEstadoOrdenField;
            }
            set {
                this.idEstadoOrdenField = value;
                this.RaisePropertyChanged("idEstadoOrden");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idEstadoOrdenSpecified {
            get {
                return this.idEstadoOrdenFieldSpecified;
            }
            set {
                this.idEstadoOrdenFieldSpecified = value;
                this.RaisePropertyChanged("idEstadoOrdenSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int numeroItems {
            get {
                return this.numeroItemsField;
            }
            set {
                this.numeroItemsField = value;
                this.RaisePropertyChanged("numeroItems");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroItemsSpecified {
            get {
                return this.numeroItemsFieldSpecified;
            }
            set {
                this.numeroItemsFieldSpecified = value;
                this.RaisePropertyChanged("numeroItemsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalSpecified {
            get {
                return this.totalFieldSpecified;
            }
            set {
                this.totalFieldSpecified = value;
                this.RaisePropertyChanged("totalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public Usuario cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
                this.RaisePropertyChanged("cliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        [System.Xml.Serialization.XmlArrayItemAttribute("items", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Item[] listaItems {
            get {
                return this.listaItemsField;
            }
            set {
                this.listaItemsField = value;
                this.RaisePropertyChanged("listaItems");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kallsony.com/entidad/usuario")]
    public partial class Usuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreUsuarioField;
        
        private string nombreField;
        
        private string apellidoField;
        
        private string tipoDocumentoField;
        
        private string numeroDocumentoField;
        
        private string correoElectronicoField;
        
        private string telefonoField;
        
        private Direccion direccionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nombreUsuario {
            get {
                return this.nombreUsuarioField;
            }
            set {
                this.nombreUsuarioField = value;
                this.RaisePropertyChanged("nombreUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
                this.RaisePropertyChanged("apellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
                this.RaisePropertyChanged("tipoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string numeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                this.numeroDocumentoField = value;
                this.RaisePropertyChanged("numeroDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string correoElectronico {
            get {
                return this.correoElectronicoField;
            }
            set {
                this.correoElectronicoField = value;
                this.RaisePropertyChanged("correoElectronico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public Direccion direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kallsony.com/entidad/direccion")]
    public partial class Direccion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroField;
        
        private string ciudadField;
        
        private string departamentoField;
        
        private int idCiudadField;
        
        private bool idCiudadFieldSpecified;
        
        private int idDepartamentoField;
        
        private bool idDepartamentoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ciudad {
            get {
                return this.ciudadField;
            }
            set {
                this.ciudadField = value;
                this.RaisePropertyChanged("ciudad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string departamento {
            get {
                return this.departamentoField;
            }
            set {
                this.departamentoField = value;
                this.RaisePropertyChanged("departamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idCiudad {
            get {
                return this.idCiudadField;
            }
            set {
                this.idCiudadField = value;
                this.RaisePropertyChanged("idCiudad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idCiudadSpecified {
            get {
                return this.idCiudadFieldSpecified;
            }
            set {
                this.idCiudadFieldSpecified = value;
                this.RaisePropertyChanged("idCiudadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idDepartamento {
            get {
                return this.idDepartamentoField;
            }
            set {
                this.idDepartamentoField = value;
                this.RaisePropertyChanged("idDepartamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idDepartamentoSpecified {
            get {
                return this.idDepartamentoFieldSpecified;
            }
            set {
                this.idDepartamentoFieldSpecified = value;
                this.RaisePropertyChanged("idDepartamentoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kallsony.com/operacion/consultaorden")]
    public partial class ConsultaOrdenSalida : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Orden[] listaOrdenesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("orden", IsNullable=false)]
        public Orden[] listaOrdenes {
            get {
                return this.listaOrdenesField;
            }
            set {
                this.listaOrdenesField = value;
                this.RaisePropertyChanged("listaOrdenes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kallsony.com/operacion/consultaorden")]
    public partial class ConsultaOrdenEntrada : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idOrdenField;
        
        private bool idOrdenFieldSpecified;
        
        private string estadoOrdenField;
        
        private Usuario clienteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int idOrden {
            get {
                return this.idOrdenField;
            }
            set {
                this.idOrdenField = value;
                this.RaisePropertyChanged("idOrden");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idOrdenSpecified {
            get {
                return this.idOrdenFieldSpecified;
            }
            set {
                this.idOrdenFieldSpecified = value;
                this.RaisePropertyChanged("idOrdenSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string estadoOrden {
            get {
                return this.estadoOrdenField;
            }
            set {
                this.estadoOrdenField = value;
                this.RaisePropertyChanged("estadoOrden");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Usuario cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
                this.RaisePropertyChanged("cliente");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.kallsony.com/final/operacion/consultaorden", ConfigurationName="ServiceOrdenes.PortOrden")]
    public interface PortOrden {
        
        // CODEGEN: Generating message contract since the operation consultarOrden is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kallsony.com/final/operacion/consultaorden/consultarOrden", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(KB2C.Data.ServiceOrdenes.Falta), Action="http://www.kallsony.com/final/operacion/consultaorden/consultarOrden", Name="falta", Namespace="http://www.kallsony.com/util/falta")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        KB2C.Data.ServiceOrdenes.consultarOrdenResponse consultarOrden(KB2C.Data.ServiceOrdenes.consultarOrdenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kallsony.com/final/operacion/consultaorden/consultarOrden", ReplyAction="*")]
        System.Threading.Tasks.Task<KB2C.Data.ServiceOrdenes.consultarOrdenResponse> consultarOrdenAsync(KB2C.Data.ServiceOrdenes.consultarOrdenRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarOrdenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.kallsony.com/operacion/consultaorden", Order=0)]
        public KB2C.Data.ServiceOrdenes.ConsultaOrdenEntrada consultaOrdenEntrada;
        
        public consultarOrdenRequest() {
        }
        
        public consultarOrdenRequest(KB2C.Data.ServiceOrdenes.ConsultaOrdenEntrada consultaOrdenEntrada) {
            this.consultaOrdenEntrada = consultaOrdenEntrada;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarOrdenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.kallsony.com/operacion/consultaorden", Order=0)]
        public KB2C.Data.ServiceOrdenes.ConsultaOrdenSalida consultaOrdenSalida;
        
        public consultarOrdenResponse() {
        }
        
        public consultarOrdenResponse(KB2C.Data.ServiceOrdenes.ConsultaOrdenSalida consultaOrdenSalida) {
            this.consultaOrdenSalida = consultaOrdenSalida;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PortOrdenChannel : KB2C.Data.ServiceOrdenes.PortOrden, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PortOrdenClient : System.ServiceModel.ClientBase<KB2C.Data.ServiceOrdenes.PortOrden>, KB2C.Data.ServiceOrdenes.PortOrden {
        
        public PortOrdenClient() {
        }
        
        public PortOrdenClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PortOrdenClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PortOrdenClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PortOrdenClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KB2C.Data.ServiceOrdenes.consultarOrdenResponse KB2C.Data.ServiceOrdenes.PortOrden.consultarOrden(KB2C.Data.ServiceOrdenes.consultarOrdenRequest request) {
            return base.Channel.consultarOrden(request);
        }
        
        public KB2C.Data.ServiceOrdenes.ConsultaOrdenSalida consultarOrden(KB2C.Data.ServiceOrdenes.ConsultaOrdenEntrada consultaOrdenEntrada) {
            KB2C.Data.ServiceOrdenes.consultarOrdenRequest inValue = new KB2C.Data.ServiceOrdenes.consultarOrdenRequest();
            inValue.consultaOrdenEntrada = consultaOrdenEntrada;
            KB2C.Data.ServiceOrdenes.consultarOrdenResponse retVal = ((KB2C.Data.ServiceOrdenes.PortOrden)(this)).consultarOrden(inValue);
            return retVal.consultaOrdenSalida;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KB2C.Data.ServiceOrdenes.consultarOrdenResponse> KB2C.Data.ServiceOrdenes.PortOrden.consultarOrdenAsync(KB2C.Data.ServiceOrdenes.consultarOrdenRequest request) {
            return base.Channel.consultarOrdenAsync(request);
        }
        
        public System.Threading.Tasks.Task<KB2C.Data.ServiceOrdenes.consultarOrdenResponse> consultarOrdenAsync(KB2C.Data.ServiceOrdenes.ConsultaOrdenEntrada consultaOrdenEntrada) {
            KB2C.Data.ServiceOrdenes.consultarOrdenRequest inValue = new KB2C.Data.ServiceOrdenes.consultarOrdenRequest();
            inValue.consultaOrdenEntrada = consultaOrdenEntrada;
            return ((KB2C.Data.ServiceOrdenes.PortOrden)(this)).consultarOrdenAsync(inValue);
        }
    }
}
