<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../Producto.wsdl"/>
      <rootElement name="consultaProductoEntrada" namespace="http://www.kallsony.com/operacion/consultaproducto"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../BPELProductos.wsdl"/>
      <rootElement name="consultaProductoEntrada" namespace="http://www.kallsony.com/operacion/consultaproducto"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 140919.1004.0161) AT [MON MAR 02 11:47:58 COT 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ns0="http://www.kallsony.com/entidad/producto"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:client="http://xmlns.oracle.com/kallSonysApp/productos/BPELProductos"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:ns1="http://www.kallsony.com/util/filtro"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:wkcuf="http://www.kallsony.com/util/falta"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:tns="http://www.kallsony.com/final/operacion/consultaproducto"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                xmlns:wkcoc="http://www.kallsony.com/operacion/consultaproducto"
                exclude-result-prefixes="xsi xsl soap ns0 ns1 wkcuf xsd tns wkcoc plnk wsdl client xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <wkcoc:consultaProductoEntrada>
      <wkcoc:filtroProducto>
        <ns1:tipoFiltro>
          <xsl:value-of select="/wkcoc:consultaProductoEntrada/wkcoc:filtroProducto/ns1:tipoFiltro"/>
        </ns1:tipoFiltro>
        <ns1:valorFiltro>
          <xsl:value-of select="/wkcoc:consultaProductoEntrada/wkcoc:filtroProducto/ns1:valorFiltro"/>
        </ns1:valorFiltro>
        <ns1:pagina>
          <xsl:value-of select="/wkcoc:consultaProductoEntrada/wkcoc:filtroProducto/ns1:pagina"/>
        </ns1:pagina>
      </wkcoc:filtroProducto>
    </wkcoc:consultaProductoEntrada>
  </xsl:template>
</xsl:stylesheet>
