<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../Producto.wsdl"/>
      <rootElement name="consultaProductoEntrada" namespace="http://www.kallsony.com/operacion/consultaproducto"/>
    </source>
    <source type="WSDL">
      <schema location="../getProductos.wsdl"/>
      <rootElement name="ProductoCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/getProductos"/>
      <param name="Invokeproductos_OutputVariable.ProductoCollection" />
    </source>
    <source type="WSDL">
      <schema location="../getCountProduct.wsdl"/>
      <rootElement name="getCountProductOutput" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/getCountProduct"/>
      <param name="Invoke_getCountProduct_OutputVariable.getCountProductOutput" />
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../Producto.wsdl"/>
      <rootElement name="consultaProductoSalida" namespace="http://www.kallsony.com/operacion/consultaproducto"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 140919.1004.0161) AT [THU MAR 12 11:22:01 COT 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns3="http://xmlns.oracle.com/pcbpel/adapter/db/kallSonysApp/productos/getCountProduct"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/kallSonysApp/productos/getProductos"
                xmlns:ns0="http://www.kallsony.com/entidad/producto"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:ns1="http://www.kallsony.com/util/filtro"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/getProductos"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:wkcuf="http://www.kallsony.com/util/falta"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:tns="http://www.kallsony.com/final/operacion/consultaproducto"
                xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/getCountProduct"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:wkcoc="http://www.kallsony.com/operacion/consultaproducto"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl ns3 plt soap wsdl ns2 ns0 ns1 top wkcuf tns db xsd wkcoc xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:param name="Invokeproductos_OutputVariable.ProductoCollection"/>
  <xsl:param name="Invoke_getCountProduct_OutputVariable.getCountProductOutput"/>
  <xsl:template match="/">
    <wkcoc:consultaProductoSalida>
      <wkcoc:respuestaFiltro>
        <ns1:totalElementos>
          <xsl:value-of select="$Invoke_getCountProduct_OutputVariable.getCountProductOutput/db:getCountProductOutput/db:total"/>
        </ns1:totalElementos>
        <ns1:pagina>
          <xsl:value-of select="/wkcoc:consultaProductoEntrada/wkcoc:filtroProducto/ns1:pagina"/>
        </ns1:pagina>
      </wkcoc:respuestaFiltro>
      <wkcoc:listaProductos>
        <xsl:for-each select="$Invokeproductos_OutputVariable.ProductoCollection/top:ProductoCollection/top:Producto">
          <wkcoc:producto>
            <ns0:idProducto>
              <xsl:value-of select="top:IdProducto"/>
            </ns0:idProducto>
            <ns0:codigoProducto>
              <xsl:value-of select="top:CodigoProducto"/>
            </ns0:codigoProducto>
            <ns0:nombreProducto>
              <xsl:value-of select="top:NombreProducto"/>
            </ns0:nombreProducto>
            <ns0:descripcionProducto>
              <xsl:value-of select="top:DescripcionProducto"/>
            </ns0:descripcionProducto>
            <ns0:fabricanteProducto>
              <xsl:value-of select="top:NombreFabricante"/>
            </ns0:fabricanteProducto>
            <ns0:nombreImagenProducto>
              <xsl:value-of select="top:NombreImagenProducto"/>
            </ns0:nombreImagenProducto>
            <ns0:precioProducto>
              <xsl:value-of select="top:PrecioUnitario"/>
            </ns0:precioProducto>
            <ns0:tipoProducto>
              <ns0:subCategoria>
                <ns0:idTipo>
                  <xsl:value-of select="top:IdSubcategoria"/>
                </ns0:idTipo>
              </ns0:subCategoria>
            </ns0:tipoProducto>
          </wkcoc:producto>
        </xsl:for-each>
      </wkcoc:listaProductos>
    </wkcoc:consultaProductoSalida>
  </xsl:template>
</xsl:stylesheet>
