//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KB2C.Data.ServiceCompra {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kallsony.com/util/falta")]
    public partial class Falta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idErrorField;
        
        private bool idErrorFieldSpecified;
        
        private string nombreErrorField;
        
        private string descripcionErrorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long idError {
            get {
                return this.idErrorField;
            }
            set {
                this.idErrorField = value;
                this.RaisePropertyChanged("idError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idErrorSpecified {
            get {
                return this.idErrorFieldSpecified;
            }
            set {
                this.idErrorFieldSpecified = value;
                this.RaisePropertyChanged("idErrorSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string nombreError {
            get {
                return this.nombreErrorField;
            }
            set {
                this.nombreErrorField = value;
                this.RaisePropertyChanged("nombreError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string descripcionError {
            get {
                return this.descripcionErrorField;
            }
            set {
                this.descripcionErrorField = value;
                this.RaisePropertyChanged("descripcionError");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kallsony.com/operacion/registrarcompra")]
    public partial class RegistrarCompraSalida : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idPreOrdenField;
        
        private bool estadoTarjetaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string idPreOrden {
            get {
                return this.idPreOrdenField;
            }
            set {
                this.idPreOrdenField = value;
                this.RaisePropertyChanged("idPreOrden");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool estadoTarjeta {
            get {
                return this.estadoTarjetaField;
            }
            set {
                this.estadoTarjetaField = value;
                this.RaisePropertyChanged("estadoTarjeta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kallsony.com/entidad/producto")]
    public partial class Tipo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idTipoField;
        
        private bool idTipoFieldSpecified;
        
        private string nombreTipoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idTipo {
            get {
                return this.idTipoField;
            }
            set {
                this.idTipoField = value;
                this.RaisePropertyChanged("idTipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idTipoSpecified {
            get {
                return this.idTipoFieldSpecified;
            }
            set {
                this.idTipoFieldSpecified = value;
                this.RaisePropertyChanged("idTipoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombreTipo {
            get {
                return this.nombreTipoField;
            }
            set {
                this.nombreTipoField = value;
                this.RaisePropertyChanged("nombreTipo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kallsony.com/entidad/producto")]
    public partial class TipoProducto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Tipo categoriaField;
        
        private Tipo subCategoriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Tipo categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
                this.RaisePropertyChanged("categoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Tipo subCategoria {
            get {
                return this.subCategoriaField;
            }
            set {
                this.subCategoriaField = value;
                this.RaisePropertyChanged("subCategoria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kallsony.com/entidad/producto")]
    public partial class Producto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idProductoField;
        
        private bool idProductoFieldSpecified;
        
        private string codigoProductoField;
        
        private string nombreProductoField;
        
        private string descripcionProductoField;
        
        private string fabricanteProductoField;
        
        private string nombreImagenProductoField;
        
        private float precioProductoField;
        
        private bool precioProductoFieldSpecified;
        
        private TipoProducto tipoProductoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long idProducto {
            get {
                return this.idProductoField;
            }
            set {
                this.idProductoField = value;
                this.RaisePropertyChanged("idProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idProductoSpecified {
            get {
                return this.idProductoFieldSpecified;
            }
            set {
                this.idProductoFieldSpecified = value;
                this.RaisePropertyChanged("idProductoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigoProducto {
            get {
                return this.codigoProductoField;
            }
            set {
                this.codigoProductoField = value;
                this.RaisePropertyChanged("codigoProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombreProducto {
            get {
                return this.nombreProductoField;
            }
            set {
                this.nombreProductoField = value;
                this.RaisePropertyChanged("nombreProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string descripcionProducto {
            get {
                return this.descripcionProductoField;
            }
            set {
                this.descripcionProductoField = value;
                this.RaisePropertyChanged("descripcionProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string fabricanteProducto {
            get {
                return this.fabricanteProductoField;
            }
            set {
                this.fabricanteProductoField = value;
                this.RaisePropertyChanged("fabricanteProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombreImagenProducto {
            get {
                return this.nombreImagenProductoField;
            }
            set {
                this.nombreImagenProductoField = value;
                this.RaisePropertyChanged("nombreImagenProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public float precioProducto {
            get {
                return this.precioProductoField;
            }
            set {
                this.precioProductoField = value;
                this.RaisePropertyChanged("precioProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool precioProductoSpecified {
            get {
                return this.precioProductoFieldSpecified;
            }
            set {
                this.precioProductoFieldSpecified = value;
                this.RaisePropertyChanged("precioProductoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public TipoProducto tipoProducto {
            get {
                return this.tipoProductoField;
            }
            set {
                this.tipoProductoField = value;
                this.RaisePropertyChanged("tipoProducto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kallsony.com/entidad/orden")]
    public partial class Item : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cantidadField;
        
        private bool tipoField;
        
        private int idCampaniaField;
        
        private bool idCampaniaFieldSpecified;
        
        private Producto productoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idCampania {
            get {
                return this.idCampaniaField;
            }
            set {
                this.idCampaniaField = value;
                this.RaisePropertyChanged("idCampania");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idCampaniaSpecified {
            get {
                return this.idCampaniaFieldSpecified;
            }
            set {
                this.idCampaniaFieldSpecified = value;
                this.RaisePropertyChanged("idCampaniaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public Producto producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
                this.RaisePropertyChanged("producto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kallsony.com/entidad/orden")]
    public partial class Orden : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idOrdenField;
        
        private bool idOrdenFieldSpecified;
        
        private string fechaOrdenField;
        
        private bool fechaOrdenFieldSpecified;
        
        private string estadoOrdenField;
        
        private int idEstadoOrdenField;
        
        private bool idEstadoOrdenFieldSpecified;
        
        private int numeroItemsField;
        
        private bool numeroItemsFieldSpecified;
        
        private double totalField;
        
        private bool totalFieldSpecified;
        
        private Usuario clienteField;
        
        private Item[] listaItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idOrden {
            get {
                return this.idOrdenField;
            }
            set {
                this.idOrdenField = value;
                this.RaisePropertyChanged("idOrden");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idOrdenSpecified {
            get {
                return this.idOrdenFieldSpecified;
            }
            set {
                this.idOrdenFieldSpecified = value;
                this.RaisePropertyChanged("idOrdenSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fechaOrden {
            get {
                return this.fechaOrdenField;
            }
            set {
                this.fechaOrdenField = value;
                this.RaisePropertyChanged("fechaOrden");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaOrdenSpecified {
            get {
                return this.fechaOrdenFieldSpecified;
            }
            set {
                this.fechaOrdenFieldSpecified = value;
                this.RaisePropertyChanged("fechaOrdenSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string estadoOrden {
            get {
                return this.estadoOrdenField;
            }
            set {
                this.estadoOrdenField = value;
                this.RaisePropertyChanged("estadoOrden");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idEstadoOrden {
            get {
                return this.idEstadoOrdenField;
            }
            set {
                this.idEstadoOrdenField = value;
                this.RaisePropertyChanged("idEstadoOrden");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idEstadoOrdenSpecified {
            get {
                return this.idEstadoOrdenFieldSpecified;
            }
            set {
                this.idEstadoOrdenFieldSpecified = value;
                this.RaisePropertyChanged("idEstadoOrdenSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int numeroItems {
            get {
                return this.numeroItemsField;
            }
            set {
                this.numeroItemsField = value;
                this.RaisePropertyChanged("numeroItems");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroItemsSpecified {
            get {
                return this.numeroItemsFieldSpecified;
            }
            set {
                this.numeroItemsFieldSpecified = value;
                this.RaisePropertyChanged("numeroItemsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalSpecified {
            get {
                return this.totalFieldSpecified;
            }
            set {
                this.totalFieldSpecified = value;
                this.RaisePropertyChanged("totalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public Usuario cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
                this.RaisePropertyChanged("cliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        [System.Xml.Serialization.XmlArrayItemAttribute("items", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Item[] listaItems {
            get {
                return this.listaItemsField;
            }
            set {
                this.listaItemsField = value;
                this.RaisePropertyChanged("listaItems");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kallsony.com/entidad/usuario")]
    public partial class Usuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreUsuarioField;
        
        private string nombreField;
        
        private string apellidoField;
        
        private string tipoDocumentoField;
        
        private string numeroDocumentoField;
        
        private string correoElectronicoField;
        
        private string telefonoField;
        
        private Direccion direccionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nombreUsuario {
            get {
                return this.nombreUsuarioField;
            }
            set {
                this.nombreUsuarioField = value;
                this.RaisePropertyChanged("nombreUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
                this.RaisePropertyChanged("apellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
                this.RaisePropertyChanged("tipoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string numeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                this.numeroDocumentoField = value;
                this.RaisePropertyChanged("numeroDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string correoElectronico {
            get {
                return this.correoElectronicoField;
            }
            set {
                this.correoElectronicoField = value;
                this.RaisePropertyChanged("correoElectronico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public Direccion direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kallsony.com/entidad/direccion")]
    public partial class Direccion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroField;
        
        private string ciudadField;
        
        private string departamentoField;
        
        private int idCiudadField;
        
        private int idDepartamentoField;
        
        private int idPaisField;
        
        private string paisField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ciudad {
            get {
                return this.ciudadField;
            }
            set {
                this.ciudadField = value;
                this.RaisePropertyChanged("ciudad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string departamento {
            get {
                return this.departamentoField;
            }
            set {
                this.departamentoField = value;
                this.RaisePropertyChanged("departamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idCiudad {
            get {
                return this.idCiudadField;
            }
            set {
                this.idCiudadField = value;
                this.RaisePropertyChanged("idCiudad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idDepartamento {
            get {
                return this.idDepartamentoField;
            }
            set {
                this.idDepartamentoField = value;
                this.RaisePropertyChanged("idDepartamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idPais {
            get {
                return this.idPaisField;
            }
            set {
                this.idPaisField = value;
                this.RaisePropertyChanged("idPais");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
                this.RaisePropertyChanged("pais");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kallsony.com/entidad/tarjeta")]
    public partial class Tarjeta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreTitularField;
        
        private string numeroTarjetaField;
        
        private string codigoSeguridadField;

        private string fechaExpiracionField;
        
        private bool fechaExpiracionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nombreTitular {
            get {
                return this.nombreTitularField;
            }
            set {
                this.nombreTitularField = value;
                this.RaisePropertyChanged("nombreTitular");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string numeroTarjeta {
            get {
                return this.numeroTarjetaField;
            }
            set {
                this.numeroTarjetaField = value;
                this.RaisePropertyChanged("numeroTarjeta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codigoSeguridad {
            get {
                return this.codigoSeguridadField;
            }
            set {
                this.codigoSeguridadField = value;
                this.RaisePropertyChanged("codigoSeguridad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string fechaExpiracion {
            get {
                return this.fechaExpiracionField;
            }
            set {
                this.fechaExpiracionField = value;
                this.RaisePropertyChanged("fechaExpiracion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaExpiracionSpecified {
            get {
                return this.fechaExpiracionFieldSpecified;
            }
            set {
                this.fechaExpiracionFieldSpecified = value;
                this.RaisePropertyChanged("fechaExpiracionSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kallsony.com/entidad/compra")]
    public partial class Compra : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Tarjeta tarjetaField;
        
        private bool envioTitularField;
        
        private bool envioTitularFieldSpecified;
        
        private Usuario usuarioEnvioField;
        
        private Orden ordenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Tarjeta tarjeta {
            get {
                return this.tarjetaField;
            }
            set {
                this.tarjetaField = value;
                this.RaisePropertyChanged("tarjeta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool envioTitular {
            get {
                return this.envioTitularField;
            }
            set {
                this.envioTitularField = value;
                this.RaisePropertyChanged("envioTitular");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool envioTitularSpecified {
            get {
                return this.envioTitularFieldSpecified;
            }
            set {
                this.envioTitularFieldSpecified = value;
                this.RaisePropertyChanged("envioTitularSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public Usuario usuarioEnvio {
            get {
                return this.usuarioEnvioField;
            }
            set {
                this.usuarioEnvioField = value;
                this.RaisePropertyChanged("usuarioEnvio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public Orden orden {
            get {
                return this.ordenField;
            }
            set {
                this.ordenField = value;
                this.RaisePropertyChanged("orden");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kallsony.com/operacion/registrarcompra")]
    public partial class RegistrarCompraEntrada : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Compra compraField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Compra compra {
            get {
                return this.compraField;
            }
            set {
                this.compraField = value;
                this.RaisePropertyChanged("compra");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.kallsony.com/final/operacion/registrarcompra", ConfigurationName="ServiceCompra.PortCompra")]
    public interface PortCompra {
        
        // CODEGEN: Generating message contract since the operation registrarCompra is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kallsony.com/final/operacion/registrarcompra/registrarCompra", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(KB2C.Data.ServiceCompra.Falta), Action="http://www.kallsony.com/final/operacion/registrarcompra/registrarCompra", Name="falta", Namespace="http://www.kallsony.com/util/falta")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        KB2C.Data.ServiceCompra.registrarCompraResponse registrarCompra(KB2C.Data.ServiceCompra.registrarCompraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kallsony.com/final/operacion/registrarcompra/registrarCompra", ReplyAction="*")]
        System.Threading.Tasks.Task<KB2C.Data.ServiceCompra.registrarCompraResponse> registrarCompraAsync(KB2C.Data.ServiceCompra.registrarCompraRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarCompraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.kallsony.com/operacion/registrarcompra", Order=0)]
        public KB2C.Data.ServiceCompra.RegistrarCompraEntrada registrarCompraEntrada;
        
        public registrarCompraRequest() {
        }
        
        public registrarCompraRequest(KB2C.Data.ServiceCompra.RegistrarCompraEntrada registrarCompraEntrada) {
            this.registrarCompraEntrada = registrarCompraEntrada;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarCompraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.kallsony.com/operacion/registrarcompra", Order=0)]
        public KB2C.Data.ServiceCompra.RegistrarCompraSalida registrarCompraSalida;
        
        public registrarCompraResponse() {
        }
        
        public registrarCompraResponse(KB2C.Data.ServiceCompra.RegistrarCompraSalida registrarCompraSalida) {
            this.registrarCompraSalida = registrarCompraSalida;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PortCompraChannel : KB2C.Data.ServiceCompra.PortCompra, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PortCompraClient : System.ServiceModel.ClientBase<KB2C.Data.ServiceCompra.PortCompra>, KB2C.Data.ServiceCompra.PortCompra {
        
        public PortCompraClient() {
        }
        
        public PortCompraClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PortCompraClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PortCompraClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PortCompraClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KB2C.Data.ServiceCompra.registrarCompraResponse KB2C.Data.ServiceCompra.PortCompra.registrarCompra(KB2C.Data.ServiceCompra.registrarCompraRequest request) {
            return base.Channel.registrarCompra(request);
        }
        
        public KB2C.Data.ServiceCompra.RegistrarCompraSalida registrarCompra(KB2C.Data.ServiceCompra.RegistrarCompraEntrada registrarCompraEntrada) {
            KB2C.Data.ServiceCompra.registrarCompraRequest inValue = new KB2C.Data.ServiceCompra.registrarCompraRequest();
            inValue.registrarCompraEntrada = registrarCompraEntrada;
            KB2C.Data.ServiceCompra.registrarCompraResponse retVal = ((KB2C.Data.ServiceCompra.PortCompra)(this)).registrarCompra(inValue);
            return retVal.registrarCompraSalida;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KB2C.Data.ServiceCompra.registrarCompraResponse> KB2C.Data.ServiceCompra.PortCompra.registrarCompraAsync(KB2C.Data.ServiceCompra.registrarCompraRequest request) {
            return base.Channel.registrarCompraAsync(request);
        }
        
        public System.Threading.Tasks.Task<KB2C.Data.ServiceCompra.registrarCompraResponse> registrarCompraAsync(KB2C.Data.ServiceCompra.RegistrarCompraEntrada registrarCompraEntrada) {
            KB2C.Data.ServiceCompra.registrarCompraRequest inValue = new KB2C.Data.ServiceCompra.registrarCompraRequest();
            inValue.registrarCompraEntrada = registrarCompraEntrada;
            return ((KB2C.Data.ServiceCompra.PortCompra)(this)).registrarCompraAsync(inValue);
        }
    }
}
