//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KB2C.Data.ServiceCampanias {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kallsony.com/util/falta")]
    public partial class Falta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idErrorField;
        
        private bool idErrorFieldSpecified;
        
        private string nombreErrorField;
        
        private string descripcionErrorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long idError {
            get {
                return this.idErrorField;
            }
            set {
                this.idErrorField = value;
                this.RaisePropertyChanged("idError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idErrorSpecified {
            get {
                return this.idErrorFieldSpecified;
            }
            set {
                this.idErrorFieldSpecified = value;
                this.RaisePropertyChanged("idErrorSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string nombreError {
            get {
                return this.nombreErrorField;
            }
            set {
                this.nombreErrorField = value;
                this.RaisePropertyChanged("nombreError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string descripcionError {
            get {
                return this.descripcionErrorField;
            }
            set {
                this.descripcionErrorField = value;
                this.RaisePropertyChanged("descripcionError");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kallsony.com/entidad/producto")]
    public partial class Tipo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idTipoField;
        
        private bool idTipoFieldSpecified;
        
        private string nombreTipoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idTipo {
            get {
                return this.idTipoField;
            }
            set {
                this.idTipoField = value;
                this.RaisePropertyChanged("idTipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idTipoSpecified {
            get {
                return this.idTipoFieldSpecified;
            }
            set {
                this.idTipoFieldSpecified = value;
                this.RaisePropertyChanged("idTipoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombreTipo {
            get {
                return this.nombreTipoField;
            }
            set {
                this.nombreTipoField = value;
                this.RaisePropertyChanged("nombreTipo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kallsony.com/entidad/producto")]
    public partial class TipoProducto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Tipo categoriaField;
        
        private Tipo subCategoriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Tipo categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
                this.RaisePropertyChanged("categoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Tipo subCategoria {
            get {
                return this.subCategoriaField;
            }
            set {
                this.subCategoriaField = value;
                this.RaisePropertyChanged("subCategoria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kallsony.com/entidad/producto")]
    public partial class Producto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idProductoField;
        
        private bool idProductoFieldSpecified;
        
        private string codigoProductoField;
        
        private string nombreProductoField;
        
        private string descripcionProductoField;
        
        private string fabricanteProductoField;
        
        private string nombreImagenProductoField;
        
        private float precioProductoField;
        
        private bool precioProductoFieldSpecified;
        
        private TipoProducto tipoProductoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long idProducto {
            get {
                return this.idProductoField;
            }
            set {
                this.idProductoField = value;
                this.RaisePropertyChanged("idProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idProductoSpecified {
            get {
                return this.idProductoFieldSpecified;
            }
            set {
                this.idProductoFieldSpecified = value;
                this.RaisePropertyChanged("idProductoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigoProducto {
            get {
                return this.codigoProductoField;
            }
            set {
                this.codigoProductoField = value;
                this.RaisePropertyChanged("codigoProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombreProducto {
            get {
                return this.nombreProductoField;
            }
            set {
                this.nombreProductoField = value;
                this.RaisePropertyChanged("nombreProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string descripcionProducto {
            get {
                return this.descripcionProductoField;
            }
            set {
                this.descripcionProductoField = value;
                this.RaisePropertyChanged("descripcionProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string fabricanteProducto {
            get {
                return this.fabricanteProductoField;
            }
            set {
                this.fabricanteProductoField = value;
                this.RaisePropertyChanged("fabricanteProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombreImagenProducto {
            get {
                return this.nombreImagenProductoField;
            }
            set {
                this.nombreImagenProductoField = value;
                this.RaisePropertyChanged("nombreImagenProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public float precioProducto {
            get {
                return this.precioProductoField;
            }
            set {
                this.precioProductoField = value;
                this.RaisePropertyChanged("precioProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool precioProductoSpecified {
            get {
                return this.precioProductoFieldSpecified;
            }
            set {
                this.precioProductoFieldSpecified = value;
                this.RaisePropertyChanged("precioProductoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public TipoProducto tipoProducto {
            get {
                return this.tipoProductoField;
            }
            set {
                this.tipoProductoField = value;
                this.RaisePropertyChanged("tipoProducto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kallsony.com/entidad/campania")]
    public partial class ProductoCampania : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int descuentoCampaniaField;
        
        private bool descuentoCampaniaFieldSpecified;
        
        private Producto productoCampaniaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int descuentoCampania {
            get {
                return this.descuentoCampaniaField;
            }
            set {
                this.descuentoCampaniaField = value;
                this.RaisePropertyChanged("descuentoCampania");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool descuentoCampaniaSpecified {
            get {
                return this.descuentoCampaniaFieldSpecified;
            }
            set {
                this.descuentoCampaniaFieldSpecified = value;
                this.RaisePropertyChanged("descuentoCampaniaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Producto productoCampania {
            get {
                return this.productoCampaniaField;
            }
            set {
                this.productoCampaniaField = value;
                this.RaisePropertyChanged("productoCampania");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kallsony.com/entidad/campania")]
    public partial class Campania : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idCampaniaField;
        
        private bool idCampaniaFieldSpecified;
        
        private string nombreCampaniaField;
        
        private System.DateTime fechaInicioCampaniaField;
        
        private bool fechaInicioCampaniaFieldSpecified;
        
        private System.DateTime fechaFinCampaniaField;
        
        private bool fechaFinCampaniaFieldSpecified;
        
        private bool estadoCampaniaField;
        
        private bool estadoCampaniaFieldSpecified;
        
        private string imagenCampaniaField;
        
        private double valorCampaniaField;
        
        private bool valorCampaniaFieldSpecified;
        
        private ProductoCampania[] listaProductosCampaniasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idCampania {
            get {
                return this.idCampaniaField;
            }
            set {
                this.idCampaniaField = value;
                this.RaisePropertyChanged("idCampania");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idCampaniaSpecified {
            get {
                return this.idCampaniaFieldSpecified;
            }
            set {
                this.idCampaniaFieldSpecified = value;
                this.RaisePropertyChanged("idCampaniaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombreCampania {
            get {
                return this.nombreCampaniaField;
            }
            set {
                this.nombreCampaniaField = value;
                this.RaisePropertyChanged("nombreCampania");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaInicioCampania {
            get {
                return this.fechaInicioCampaniaField;
            }
            set {
                this.fechaInicioCampaniaField = value;
                this.RaisePropertyChanged("fechaInicioCampania");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInicioCampaniaSpecified {
            get {
                return this.fechaInicioCampaniaFieldSpecified;
            }
            set {
                this.fechaInicioCampaniaFieldSpecified = value;
                this.RaisePropertyChanged("fechaInicioCampaniaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaFinCampania {
            get {
                return this.fechaFinCampaniaField;
            }
            set {
                this.fechaFinCampaniaField = value;
                this.RaisePropertyChanged("fechaFinCampania");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinCampaniaSpecified {
            get {
                return this.fechaFinCampaniaFieldSpecified;
            }
            set {
                this.fechaFinCampaniaFieldSpecified = value;
                this.RaisePropertyChanged("fechaFinCampaniaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool estadoCampania {
            get {
                return this.estadoCampaniaField;
            }
            set {
                this.estadoCampaniaField = value;
                this.RaisePropertyChanged("estadoCampania");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoCampaniaSpecified {
            get {
                return this.estadoCampaniaFieldSpecified;
            }
            set {
                this.estadoCampaniaFieldSpecified = value;
                this.RaisePropertyChanged("estadoCampaniaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string imagenCampania {
            get {
                return this.imagenCampaniaField;
            }
            set {
                this.imagenCampaniaField = value;
                this.RaisePropertyChanged("imagenCampania");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double valorCampania {
            get {
                return this.valorCampaniaField;
            }
            set {
                this.valorCampaniaField = value;
                this.RaisePropertyChanged("valorCampania");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valorCampaniaSpecified {
            get {
                return this.valorCampaniaFieldSpecified;
            }
            set {
                this.valorCampaniaFieldSpecified = value;
                this.RaisePropertyChanged("valorCampaniaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        [System.Xml.Serialization.XmlArrayItemAttribute("productoCampania", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ProductoCampania[] listaProductosCampanias {
            get {
                return this.listaProductosCampaniasField;
            }
            set {
                this.listaProductosCampaniasField = value;
                this.RaisePropertyChanged("listaProductosCampanias");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kallsony.com/operacion/consultacampania")]
    public partial class ConsultaCampaniaSalida : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Campania[] campaniasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("campania", IsNullable=false)]
        public Campania[] campanias {
            get {
                return this.campaniasField;
            }
            set {
                this.campaniasField = value;
                this.RaisePropertyChanged("campanias");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kallsony.com/util/filtro")]
    public partial class FiltroCampania : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool estadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kallsony.com/operacion/consultacampania")]
    public partial class ConsultaCampaniaEntrada : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FiltroCampania filtroCampaniaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FiltroCampania filtroCampania {
            get {
                return this.filtroCampaniaField;
            }
            set {
                this.filtroCampaniaField = value;
                this.RaisePropertyChanged("filtroCampania");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.kallsony.com/final/operacion/consultacampanias", ConfigurationName="ServiceCampanias.CampaniasPort")]
    public interface CampaniasPort {
        
        // CODEGEN: Generating message contract since the operation ConsultarCampanias is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kallsony.com/final/operacion/consultacampanias/ConsultarCampanias", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(KB2C.Data.ServiceCampanias.Falta), Action="http://www.kallsony.com/final/operacion/consultacampanias/ConsultarCampanias", Name="falta", Namespace="http://www.kallsony.com/util/falta")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        KB2C.Data.ServiceCampanias.ConsultarCampaniasResponse ConsultarCampanias(KB2C.Data.ServiceCampanias.ConsultarCampaniasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kallsony.com/final/operacion/consultacampanias/ConsultarCampanias", ReplyAction="*")]
        System.Threading.Tasks.Task<KB2C.Data.ServiceCampanias.ConsultarCampaniasResponse> ConsultarCampaniasAsync(KB2C.Data.ServiceCampanias.ConsultarCampaniasRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarCampaniasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.kallsony.com/operacion/consultacampania", Order=0)]
        public KB2C.Data.ServiceCampanias.ConsultaCampaniaEntrada consultaCampaniaEntrada;
        
        public ConsultarCampaniasRequest() {
        }
        
        public ConsultarCampaniasRequest(KB2C.Data.ServiceCampanias.ConsultaCampaniaEntrada consultaCampaniaEntrada) {
            this.consultaCampaniaEntrada = consultaCampaniaEntrada;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarCampaniasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.kallsony.com/operacion/consultacampania", Order=0)]
        public KB2C.Data.ServiceCampanias.ConsultaCampaniaSalida consultaCampaniaSalida;
        
        public ConsultarCampaniasResponse() {
        }
        
        public ConsultarCampaniasResponse(KB2C.Data.ServiceCampanias.ConsultaCampaniaSalida consultaCampaniaSalida) {
            this.consultaCampaniaSalida = consultaCampaniaSalida;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CampaniasPortChannel : KB2C.Data.ServiceCampanias.CampaniasPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CampaniasPortClient : System.ServiceModel.ClientBase<KB2C.Data.ServiceCampanias.CampaniasPort>, KB2C.Data.ServiceCampanias.CampaniasPort {
        
        public CampaniasPortClient() {
        }
        
        public CampaniasPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CampaniasPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CampaniasPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CampaniasPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KB2C.Data.ServiceCampanias.ConsultarCampaniasResponse KB2C.Data.ServiceCampanias.CampaniasPort.ConsultarCampanias(KB2C.Data.ServiceCampanias.ConsultarCampaniasRequest request) {
            return base.Channel.ConsultarCampanias(request);
        }
        
        public KB2C.Data.ServiceCampanias.ConsultaCampaniaSalida ConsultarCampanias(KB2C.Data.ServiceCampanias.ConsultaCampaniaEntrada consultaCampaniaEntrada) {
            KB2C.Data.ServiceCampanias.ConsultarCampaniasRequest inValue = new KB2C.Data.ServiceCampanias.ConsultarCampaniasRequest();
            inValue.consultaCampaniaEntrada = consultaCampaniaEntrada;
            KB2C.Data.ServiceCampanias.ConsultarCampaniasResponse retVal = ((KB2C.Data.ServiceCampanias.CampaniasPort)(this)).ConsultarCampanias(inValue);
            return retVal.consultaCampaniaSalida;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KB2C.Data.ServiceCampanias.ConsultarCampaniasResponse> KB2C.Data.ServiceCampanias.CampaniasPort.ConsultarCampaniasAsync(KB2C.Data.ServiceCampanias.ConsultarCampaniasRequest request) {
            return base.Channel.ConsultarCampaniasAsync(request);
        }
        
        public System.Threading.Tasks.Task<KB2C.Data.ServiceCampanias.ConsultarCampaniasResponse> ConsultarCampaniasAsync(KB2C.Data.ServiceCampanias.ConsultaCampaniaEntrada consultaCampaniaEntrada) {
            KB2C.Data.ServiceCampanias.ConsultarCampaniasRequest inValue = new KB2C.Data.ServiceCampanias.ConsultarCampaniasRequest();
            inValue.consultaCampaniaEntrada = consultaCampaniaEntrada;
            return ((KB2C.Data.ServiceCampanias.CampaniasPort)(this)).ConsultarCampaniasAsync(inValue);
        }
    }
}
