<?binding.jca getOrden_db.jca?>
<wsdl:definitions name="getOrden" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Appkallsonys/ProjectCancelar/getOrden" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Appkallsonys/ProjectCancelar/getOrden" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/getOrden">
    <plt:partnerLinkType name="getOrden_plt">
        <plt:role name="getOrden_role">
            <plt:portType name="tns:getOrden_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/getOrden" schemaLocation="xsd/getOrden_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="getOrdenSelect_inputParameters">
        <wsdl:part name="getOrdenSelect_inputParameters" element="top:getOrdenSelect_paramOrdenInputParameters"/>
    </wsdl:message>
    <wsdl:message name="OrdenCollection_msg">
        <wsdl:part name="OrdenCollection" element="top:OrdenCollection"/>
    </wsdl:message>
    <wsdl:portType name="getOrden_ptt">
        <wsdl:operation name="getOrdenSelect">
            <wsdl:input message="tns:getOrdenSelect_inputParameters"/>
            <wsdl:output message="tns:OrdenCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
