<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../getCampanias.wsdl"/>
      <rootElement name="CampaniaCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/getCampanias"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../Campanias.wsdl"/>
      <rootElement name="consultaCampaniaSalida" namespace="http://www.kallsony.com/operacion/consultacampania"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 140919.1004.0161) AT [MON APR 27 18:21:18 COT 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ns1="http://www.kallsony.com/entidad/producto"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Appkallsonys/ProjectCampanias/getCampanias"
                xmlns:ns0="http://www.kallsony.com/final/operacion/consultacampanias"
                xmlns:ns2="http://www.kallsony.com/entidad/campania"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/getCampanias"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:ns3="http://www.kallsony.com/util/filtro"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:wkcaf="http://www.kallsony.com/util/falta"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:wkcam="http://www.kallsony.com/operacion/consultacampania"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl plt wsdl tns top xsd soap ns1 ns0 ns2 ns3 wkcaf wkcam xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <wkcam:consultaCampaniaSalida>
      <wkcam:campanias>
        <xsl:for-each select="/top:CampaniaCollection/top:Campania">
          <wkcam:campania>
            <idCampania>
              <xsl:value-of select="top:IdCampania"/>
            </idCampania>
            <xsl:if test="top:Nombre">
              <nombreCampania>
                <xsl:value-of select="top:Nombre"/>
              </nombreCampania>
            </xsl:if>
            <xsl:if test="top:FechaInicio">
              <fechaInicioCampania>
                <xsl:value-of select="top:FechaInicio"/>
              </fechaInicioCampania>
            </xsl:if>
            <xsl:if test="top:FechaFin">
              <fechaFinCampania>
                <xsl:value-of select="top:FechaFin"/>
              </fechaFinCampania>
            </xsl:if>
            <xsl:if test="top:Estado">
              <estadoCampania>
                <xsl:value-of select="top:Estado"/>
              </estadoCampania>
            </xsl:if>
            <xsl:if test="top:NombreImagenCampania">
              <imagenCampania>
                <xsl:value-of select="top:NombreImagenCampania"/>
              </imagenCampania>
            </xsl:if>
            <valorCampania>
              <xsl:value-of select="number(0)"/>
            </valorCampania>
            <listaProductosCampanias>
              <xsl:for-each select="top:ProductoxCampaniaCollection/top:ProductoxCampania">
                <productoCampania>
                  <descuentoCampania>
                    <xsl:value-of select="top:PorcentajeDescuento"/>
                  </descuentoCampania>
                  <productoCampania>
                    <idProducto>
                      <xsl:value-of select="top:IdProducto"/>
                    </idProducto>
                  </productoCampania>
                </productoCampania>
              </xsl:for-each>
            </listaProductosCampanias>
          </wkcam:campania>
        </xsl:for-each>
      </wkcam:campanias>
    </wkcam:consultaCampaniaSalida>
  </xsl:template>
</xsl:stylesheet>
