//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KB2C.Data.ServiceCategorias {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kallsony.com/util/falta")]
    public partial class Falta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idErrorField;
        
        private bool idErrorFieldSpecified;
        
        private string nombreErrorField;
        
        private string descripcionErrorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long idError {
            get {
                return this.idErrorField;
            }
            set {
                this.idErrorField = value;
                this.RaisePropertyChanged("idError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idErrorSpecified {
            get {
                return this.idErrorFieldSpecified;
            }
            set {
                this.idErrorFieldSpecified = value;
                this.RaisePropertyChanged("idErrorSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string nombreError {
            get {
                return this.nombreErrorField;
            }
            set {
                this.nombreErrorField = value;
                this.RaisePropertyChanged("nombreError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string descripcionError {
            get {
                return this.descripcionErrorField;
            }
            set {
                this.descripcionErrorField = value;
                this.RaisePropertyChanged("descripcionError");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kallsony.com/entidad/categoria")]
    public partial class SubCategoria : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Tipo tipoSubCategoriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Tipo tipoSubCategoria {
            get {
                return this.tipoSubCategoriaField;
            }
            set {
                this.tipoSubCategoriaField = value;
                this.RaisePropertyChanged("tipoSubCategoria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kallsony.com/entidad/categoria")]
    public partial class Tipo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idTipoField;
        
        private bool idTipoFieldSpecified;
        
        private string nombreTipoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idTipo {
            get {
                return this.idTipoField;
            }
            set {
                this.idTipoField = value;
                this.RaisePropertyChanged("idTipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idTipoSpecified {
            get {
                return this.idTipoFieldSpecified;
            }
            set {
                this.idTipoFieldSpecified = value;
                this.RaisePropertyChanged("idTipoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombreTipo {
            get {
                return this.nombreTipoField;
            }
            set {
                this.nombreTipoField = value;
                this.RaisePropertyChanged("nombreTipo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kallsony.com/entidad/categoria")]
    public partial class Categoria : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Tipo tipoCategoriaField;
        
        private SubCategoria[] listaSubCategoriasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Tipo tipoCategoria {
            get {
                return this.tipoCategoriaField;
            }
            set {
                this.tipoCategoriaField = value;
                this.RaisePropertyChanged("tipoCategoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("subCategoria", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SubCategoria[] listaSubCategorias {
            get {
                return this.listaSubCategoriasField;
            }
            set {
                this.listaSubCategoriasField = value;
                this.RaisePropertyChanged("listaSubCategorias");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kallsony.com/operacion/consultarcategorias")]
    public partial class ConsultaCategoriaSalida : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Categoria[] listaCategoriasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("categoria", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Categoria[] listaCategorias {
            get {
                return this.listaCategoriasField;
            }
            set {
                this.listaCategoriasField = value;
                this.RaisePropertyChanged("listaCategorias");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kallsony.com/util/filtro")]
    public partial class Filtro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tipoFiltroField;
        
        private string valorFiltroField;
        
        private int paginaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string tipoFiltro {
            get {
                return this.tipoFiltroField;
            }
            set {
                this.tipoFiltroField = value;
                this.RaisePropertyChanged("tipoFiltro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string valorFiltro {
            get {
                return this.valorFiltroField;
            }
            set {
                this.valorFiltroField = value;
                this.RaisePropertyChanged("valorFiltro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int pagina {
            get {
                return this.paginaField;
            }
            set {
                this.paginaField = value;
                this.RaisePropertyChanged("pagina");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kallsony.com/operacion/consultarcategorias")]
    public partial class ConsultaCategoriaEntrada : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Filtro filtroCategoriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Filtro filtroCategoria {
            get {
                return this.filtroCategoriaField;
            }
            set {
                this.filtroCategoriaField = value;
                this.RaisePropertyChanged("filtroCategoria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.kallsony.com/final/operacion/consultacategorias", ConfigurationName="ServiceCategorias.portCategorias")]
    public interface portCategorias {
        
        // CODEGEN: Generating message contract since the operation consultaCategorias is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kallsony.com/final/operacion/consultacategorias/consultaCategorias", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(KB2C.Data.ServiceCategorias.Falta), Action="http://www.kallsony.com/final/operacion/consultacategorias/consultaCategorias", Name="falta", Namespace="http://www.kallsony.com/util/falta")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        KB2C.Data.ServiceCategorias.consultaCategoriasResponse consultaCategorias(KB2C.Data.ServiceCategorias.consultaCategoriasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kallsony.com/final/operacion/consultacategorias/consultaCategorias", ReplyAction="*")]
        System.Threading.Tasks.Task<KB2C.Data.ServiceCategorias.consultaCategoriasResponse> consultaCategoriasAsync(KB2C.Data.ServiceCategorias.consultaCategoriasRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaCategoriasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.kallsony.com/operacion/consultarcategorias", Order=0)]
        public KB2C.Data.ServiceCategorias.ConsultaCategoriaEntrada consultaCategoriaEntrada;
        
        public consultaCategoriasRequest() {
        }
        
        public consultaCategoriasRequest(KB2C.Data.ServiceCategorias.ConsultaCategoriaEntrada consultaCategoriaEntrada) {
            this.consultaCategoriaEntrada = consultaCategoriaEntrada;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaCategoriasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.kallsony.com/operacion/consultarcategorias", Order=0)]
        public KB2C.Data.ServiceCategorias.ConsultaCategoriaSalida consultaCategoriaSalida;
        
        public consultaCategoriasResponse() {
        }
        
        public consultaCategoriasResponse(KB2C.Data.ServiceCategorias.ConsultaCategoriaSalida consultaCategoriaSalida) {
            this.consultaCategoriaSalida = consultaCategoriaSalida;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface portCategoriasChannel : KB2C.Data.ServiceCategorias.portCategorias, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class portCategoriasClient : System.ServiceModel.ClientBase<KB2C.Data.ServiceCategorias.portCategorias>, KB2C.Data.ServiceCategorias.portCategorias {
        
        public portCategoriasClient() {
        }
        
        public portCategoriasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public portCategoriasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public portCategoriasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public portCategoriasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KB2C.Data.ServiceCategorias.consultaCategoriasResponse KB2C.Data.ServiceCategorias.portCategorias.consultaCategorias(KB2C.Data.ServiceCategorias.consultaCategoriasRequest request) {
            return base.Channel.consultaCategorias(request);
        }
        
        public KB2C.Data.ServiceCategorias.ConsultaCategoriaSalida consultaCategorias(KB2C.Data.ServiceCategorias.ConsultaCategoriaEntrada consultaCategoriaEntrada) {
            KB2C.Data.ServiceCategorias.consultaCategoriasRequest inValue = new KB2C.Data.ServiceCategorias.consultaCategoriasRequest();
            inValue.consultaCategoriaEntrada = consultaCategoriaEntrada;
            KB2C.Data.ServiceCategorias.consultaCategoriasResponse retVal = ((KB2C.Data.ServiceCategorias.portCategorias)(this)).consultaCategorias(inValue);
            return retVal.consultaCategoriaSalida;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KB2C.Data.ServiceCategorias.consultaCategoriasResponse> KB2C.Data.ServiceCategorias.portCategorias.consultaCategoriasAsync(KB2C.Data.ServiceCategorias.consultaCategoriasRequest request) {
            return base.Channel.consultaCategoriasAsync(request);
        }
        
        public System.Threading.Tasks.Task<KB2C.Data.ServiceCategorias.consultaCategoriasResponse> consultaCategoriasAsync(KB2C.Data.ServiceCategorias.ConsultaCategoriaEntrada consultaCategoriaEntrada) {
            KB2C.Data.ServiceCategorias.consultaCategoriasRequest inValue = new KB2C.Data.ServiceCategorias.consultaCategoriasRequest();
            inValue.consultaCategoriaEntrada = consultaCategoriaEntrada;
            return ((KB2C.Data.ServiceCategorias.portCategorias)(this)).consultaCategoriasAsync(inValue);
        }
    }
}
