--------------------------------------------------------
--  DDL for Sequence ORDENES E ITEM_ORDEN
--------------------------------------------------------
CREATE SEQUENCE "SEQ_ORDENES" INCREMENT BY 50 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
/
CREATE SEQUENCE "SEQ_ITEMORDEN" INCREMENT BY 50 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
/
alter table ORDEN rename column IDCLIENTE to IDUSUARIO;
/
ALTER TABLE ORDEN
ADD CONSTRAINT FK_ORDEN_USUARIO
FOREIGN KEY (IDUSUARIO)
REFERENCES USUARIO(IDUSUARIO);
/
ALTER TABLE USUARIO MODIFY (NOMBRES NULL);
/
ALTER TABLE USUARIO MODIFY (APELLIDOS NULL);
/
ALTER TABLE USUARIO MODIFY (EMAIL NOT NULL);
/
ALTER TABLE USUARIO MODIFY (TIPODOCUMENTO NULL);
/
ALTER TABLE USUARIO MODIFY (NUMERODOCUMENTO NULL);
/
ALTER TABLE USUARIO MODIFY (USERNAME NULL);
/
ALTER TABLE USUARIO MODIFY (COMPRAENCOLOMBIA NULL);
/
ALTER TABLE USUARIO MODIFY (IDCATEGORIA NULL);
/
