Insert into ESTADO_ORDEN (IDESTADOORDEN,NOMBREESTADOORDEN) values ('1','CREADA');
Insert into ESTADO_ORDEN (IDESTADOORDEN,NOMBREESTADOORDEN) values ('2','APROBADA');
Insert into ESTADO_ORDEN (IDESTADOORDEN,NOMBREESTADOORDEN) values ('3','RECHAZADA');
Insert into ESTADO_ORDEN (IDESTADOORDEN,NOMBREESTADOORDEN) values ('4','ENVIADA');
Insert into ESTADO_ORDEN (IDESTADOORDEN,NOMBREESTADOORDEN) values ('5','CERRADA');
Insert into ESTADO_ORDEN (IDESTADOORDEN,NOMBREESTADOORDEN) values ('6','ANULADA');