CREATE TABLE PRODUCTOS_TOP5
(
  IDPRODUCTO_PADRE NUMERIC(10,0)
  ,IDPRODUCTO NUMERIC(10,0)
  ,CANT_ORDENES NUMBER(10,0)
);
/
ALTER TABLE "PRODUCTOS_TOP5" ADD CONSTRAINT "PRODUCTOS_TOP5_PK" PRIMARY KEY ("IDPRODUCTO_PADRE", "IDPRODUCTO");
/
COMMIT;
/
CREATE INDEX TOP5_IDPRODUCTO_IX ON PRODUCTOS_TOP5 (IDPRODUCTO_PADRE) TABLESPACE "TBS_OMS";
/
COMMIT;
/
