<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../getSpProductos.wsdl"/>
      <rootElement name="OutputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/getSpProductos"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../Producto.wsdl"/>
      <rootElement name="consultaProductoSalida" namespace="http://www.kallsony.com/operacion/consultaproducto"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 140919.1004.0161) AT [SUN MAY 24 23:02:16 COT 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/getSpProductos"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns1="http://www.kallsony.com/entidad/producto"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:ns2="http://www.kallsony.com/util/filtro"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Appkallsonys/ProjectProductos/getSpProductos"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:wkcuf="http://www.kallsony.com/util/falta"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns0="http://www.kallsony.com/final/operacion/consultaproducto"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                xmlns:wkcoc="http://www.kallsony.com/operacion/consultaproducto"
                exclude-result-prefixes="xsi xsl plt db wsdl tns xsd soap ns1 ns2 wkcuf ns0 wkcoc xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <wkcoc:consultaProductoSalida>
      <wkcoc:respuestaFiltro>
        <totalElementos>
          <xsl:value-of select="number(1)"/>
        </totalElementos>
        <pagina>
          <xsl:value-of select="number(1)"/>
        </pagina>
      </wkcoc:respuestaFiltro>
      <wkcoc:listaProductos>
        <xsl:for-each select="/db:OutputParameters/db:RowSet0/db:RowSet0_Row">
          <wkcoc:producto>
            <idProducto>
              <xsl:value-of select="db:IdProducto"/>
            </idProducto>
            <codigoProducto>
              <xsl:value-of select="db:CodigoProducto"/>
            </codigoProducto>
            <nombreProducto>
              <xsl:value-of select="db:NombreProducto"/>
            </nombreProducto>
            <descripcionProducto>
              <xsl:value-of select="db:DescripcionProducto"/>
            </descripcionProducto>
            <fabricanteProducto>
              <xsl:value-of select="db:NombreFabricante"/>
            </fabricanteProducto>
            <nombreImagenProducto>
              <xsl:value-of select="db:NombreImagenProducto"/>
            </nombreImagenProducto>
            <precioProducto>
              <xsl:value-of select="db:PrecioUnitario"/>
            </precioProducto>
            <tipoProducto>
              <subCategoria>
                <idTipo>
                  <xsl:value-of select="db:IdSubcategoria"/>
                </idTipo>
              </subCategoria>
            </tipoProducto>
          </wkcoc:producto>
        </xsl:for-each>
      </wkcoc:listaProductos>
    </wkcoc:consultaProductoSalida>
  </xsl:template>
</xsl:stylesheet>
