<?binding.jca getCampanias_db.jca?>
<wsdl:definitions name="getCampanias" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Appkallsonys/ProjectCampanias/getCampanias" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Appkallsonys/ProjectCampanias/getCampanias" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/getCampanias">
    <plt:partnerLinkType name="getCampanias_plt">
        <plt:role name="getCampanias_role">
            <plt:portType name="tns:getCampanias_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/getCampanias" schemaLocation="xsd/getCampanias_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="getCampaniasSelect_inputParameters">
        <wsdl:part name="getCampaniasSelect_inputParameters" element="top:getCampaniasSelect_estadoCampaniaInputParameters"/>
    </wsdl:message>
    <wsdl:message name="CampaniaCollection_msg">
        <wsdl:part name="CampaniaCollection" element="top:CampaniaCollection"/>
    </wsdl:message>
    <wsdl:portType name="getCampanias_ptt">
        <wsdl:operation name="getCampaniasSelect">
            <wsdl:input message="tns:getCampaniasSelect_inputParameters"/>
            <wsdl:output message="tns:CampaniaCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
