<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="Productos"
     targetNamespace="http://www.kallsony.com/final/operacion/consultaproducto"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
     xmlns:tns="http://www.kallsony.com/final/operacion/consultaproducto"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <plnk:partnerLinkType name="ServiceProductos">
        <plnk:role name="ProductosPort">
            <plnk:portType name="tns:ProductosPort"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://www.kallsony.com/final/operacion/consultaproducto" location="http://AES_PICA:7001/soa-infra/services/default/ProjectProductos/Producto.wsdl"/>
</wsdl:definitions>
