<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../Categorias.wsdl"/>
      <rootElement name="consultaCategoriaEntrada" namespace="http://www.kallsony.com/operacion/consultarcategorias"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../getCategorias.wsdl"/>
      <rootElement name="getCategoriasSelect_tipoFiltro_valorFiltro_paginaInputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/getCategorias"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 140919.1004.0161) AT [SUN MAR 22 13:12:46 COT 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/kallSonysApp/categorias/getCategorias"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/getCategorias"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:wkct="http://www.kallsony.com/operacion/consultarcategorias"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:ns1="http://www.kallsony.com/entidad/categoria"
                xmlns:ns0="http://www.kallsony.com/util/filtro"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:tns="http://www.kallsony.com/final/operacion/consultacategorias"
                xmlns:wkctf="http://www.kallsony.com/util/falta"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl soap wkct ns1 ns0 tns wkctf xsd ns2 top plt wsdl xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <top:getCategoriasSelect_tipoFiltro_valorFiltro_paginaInputParameters>
      <top:tipoFiltro>
        <xsl:value-of select="/wkct:consultaCategoriaEntrada/wkct:filtroCategoria/tipoFiltro"/>
      </top:tipoFiltro>
      <top:valorFiltro>
        <xsl:value-of select="/wkct:consultaCategoriaEntrada/wkct:filtroCategoria/valorFiltro"/>
      </top:valorFiltro>
      <top:pagina>
        <xsl:value-of select="/wkct:consultaCategoriaEntrada/wkct:filtroCategoria/pagina"/>
      </top:pagina>
    </top:getCategoriasSelect_tipoFiltro_valorFiltro_paginaInputParameters>
  </xsl:template>
</xsl:stylesheet>
