<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../CompraJMS.wsdl"/>
      <rootElement name="registrarCompraEntrada" namespace="http://www.kallsony.com/operacion/registrarcompra"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../BPELOrdenCompra.wsdl"/>
      <rootElement name="registrarCompraEntrada" namespace="http://www.kallsony.com/operacion/registrarcompra"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 140919.1004.0161) AT [SUN APR 19 18:23:48 COT 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/Appkallsonys/ProjectOrden/CompraJMS"
                xmlns:ns1="http://www.kallsony.com/entidad/compra"
                xmlns:ns3="http://www.kallsony.com/entidad/tarjeta"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns2="http://www.kallsony.com/entidad/producto"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:imp1="http://www.kallsony.com/operacion/registrarcompra"
                xmlns:client="http://xmlns.oracle.com/Appkallsonys/ProjectOrden/BPELOrdenCompra"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns4="http://www.kallsony.com/entidad/orden"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns5="http://www.kallsony.com/entidad/usuario"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns0="http://www.kallsony.com/entidad/direccion"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl tns ns1 ns3 pc plt wsdl ns2 imp1 jca ns4 ns5 ns0 xsd client xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <imp1:registrarCompraEntrada>
      <imp1:compra>
        <tarjeta>
          <xsl:if test="/imp1:registrarCompraEntrada/imp1:compra/tarjeta/nombreTitular">
            <nombreTitular>
              <xsl:value-of select="/imp1:registrarCompraEntrada/imp1:compra/tarjeta/nombreTitular"/>
            </nombreTitular>
          </xsl:if>
          <xsl:if test="/imp1:registrarCompraEntrada/imp1:compra/tarjeta/numeroTarjeta">
            <numeroTarjeta>
              <xsl:value-of select="/imp1:registrarCompraEntrada/imp1:compra/tarjeta/numeroTarjeta"/>
            </numeroTarjeta>
          </xsl:if>
          <xsl:if test="/imp1:registrarCompraEntrada/imp1:compra/tarjeta/codigoSeguridad">
            <codigoSeguridad>
              <xsl:value-of select="/imp1:registrarCompraEntrada/imp1:compra/tarjeta/codigoSeguridad"/>
            </codigoSeguridad>
          </xsl:if>
          <xsl:if test="/imp1:registrarCompraEntrada/imp1:compra/tarjeta/fechaExpiracion">
            <fechaExpiracion>
              <xsl:value-of select="/imp1:registrarCompraEntrada/imp1:compra/tarjeta/fechaExpiracion"/>
            </fechaExpiracion>
          </xsl:if>
        </tarjeta>
        <xsl:if test="/imp1:registrarCompraEntrada/imp1:compra/envioTitular">
          <envioTitular>
            <xsl:value-of select="/imp1:registrarCompraEntrada/imp1:compra/envioTitular"/>
          </envioTitular>
        </xsl:if>
        <xsl:if test="/imp1:registrarCompraEntrada/imp1:compra/usuarioEnvio">
          <usuarioEnvio>
            <xsl:if test="/imp1:registrarCompraEntrada/imp1:compra/usuarioEnvio/nombreUsuario">
              <nombreUsuario>
                <xsl:value-of select="/imp1:registrarCompraEntrada/imp1:compra/usuarioEnvio/nombreUsuario"/>
              </nombreUsuario>
            </xsl:if>
            <xsl:if test="/imp1:registrarCompraEntrada/imp1:compra/usuarioEnvio/nombre">
              <nombre>
                <xsl:value-of select="/imp1:registrarCompraEntrada/imp1:compra/usuarioEnvio/nombre"/>
              </nombre>
            </xsl:if>
            <xsl:if test="/imp1:registrarCompraEntrada/imp1:compra/usuarioEnvio/apellido">
              <apellido>
                <xsl:value-of select="/imp1:registrarCompraEntrada/imp1:compra/usuarioEnvio/apellido"/>
              </apellido>
            </xsl:if>
            <xsl:if test="/imp1:registrarCompraEntrada/imp1:compra/usuarioEnvio/tipoDocumento">
              <tipoDocumento>
                <xsl:value-of select="/imp1:registrarCompraEntrada/imp1:compra/usuarioEnvio/tipoDocumento"/>
              </tipoDocumento>
            </xsl:if>
            <xsl:if test="/imp1:registrarCompraEntrada/imp1:compra/usuarioEnvio/numeroDocumento">
              <numeroDocumento>
                <xsl:value-of select="/imp1:registrarCompraEntrada/imp1:compra/usuarioEnvio/numeroDocumento"/>
              </numeroDocumento>
            </xsl:if>
            <xsl:if test="/imp1:registrarCompraEntrada/imp1:compra/usuarioEnvio/correoElectronico">
              <correoElectronico>
                <xsl:value-of select="/imp1:registrarCompraEntrada/imp1:compra/usuarioEnvio/correoElectronico"/>
              </correoElectronico>
            </xsl:if>
            <xsl:if test="/imp1:registrarCompraEntrada/imp1:compra/usuarioEnvio/telefono">
              <telefono>
                <xsl:value-of select="/imp1:registrarCompraEntrada/imp1:compra/usuarioEnvio/telefono"/>
              </telefono>
            </xsl:if>
            <xsl:if test="/imp1:registrarCompraEntrada/imp1:compra/usuarioEnvio/direccion">
              <direccion>
                <xsl:if test="/imp1:registrarCompraEntrada/imp1:compra/usuarioEnvio/direccion/numero">
                  <numero>
                    <xsl:value-of select="/imp1:registrarCompraEntrada/imp1:compra/usuarioEnvio/direccion/numero"/>
                  </numero>
                </xsl:if>
                <xsl:if test="/imp1:registrarCompraEntrada/imp1:compra/usuarioEnvio/direccion/ciudad">
                  <ciudad>
                    <xsl:value-of select="/imp1:registrarCompraEntrada/imp1:compra/usuarioEnvio/direccion/ciudad"/>
                  </ciudad>
                </xsl:if>
                <xsl:if test="/imp1:registrarCompraEntrada/imp1:compra/usuarioEnvio/direccion/departamento">
                  <departamento>
                    <xsl:value-of select="/imp1:registrarCompraEntrada/imp1:compra/usuarioEnvio/direccion/departamento"/>
                  </departamento>
                </xsl:if>
                <idCiudad>
                  <xsl:value-of select="/imp1:registrarCompraEntrada/imp1:compra/usuarioEnvio/direccion/idCiudad"/>
                </idCiudad>
                <idDepartamento>
                  <xsl:value-of select="/imp1:registrarCompraEntrada/imp1:compra/usuarioEnvio/direccion/idDepartamento"/>
                </idDepartamento>
              </direccion>
            </xsl:if>
          </usuarioEnvio>
        </xsl:if>
        <xsl:if test="/imp1:registrarCompraEntrada/imp1:compra/orden">
          <orden>
            <xsl:if test="/imp1:registrarCompraEntrada/imp1:compra/orden/idOrden">
              <idOrden>
                <xsl:value-of select="/imp1:registrarCompraEntrada/imp1:compra/orden/idOrden"/>
              </idOrden>
            </xsl:if>
            <xsl:if test="/imp1:registrarCompraEntrada/imp1:compra/orden/fechaOrden">
              <fechaOrden>
                <xsl:value-of select="/imp1:registrarCompraEntrada/imp1:compra/orden/fechaOrden"/>
              </fechaOrden>
            </xsl:if>
            <xsl:if test="/imp1:registrarCompraEntrada/imp1:compra/orden/estadoOrden">
              <estadoOrden>
                <xsl:value-of select="/imp1:registrarCompraEntrada/imp1:compra/orden/estadoOrden"/>
              </estadoOrden>
            </xsl:if>
            <xsl:if test="/imp1:registrarCompraEntrada/imp1:compra/orden/idEstadoOrden">
              <idEstadoOrden>
                <xsl:value-of select="/imp1:registrarCompraEntrada/imp1:compra/orden/idEstadoOrden"/>
              </idEstadoOrden>
            </xsl:if>
            <xsl:if test="/imp1:registrarCompraEntrada/imp1:compra/orden/numeroItems">
              <numeroItems>
                <xsl:value-of select="/imp1:registrarCompraEntrada/imp1:compra/orden/numeroItems"/>
              </numeroItems>
            </xsl:if>
            <xsl:if test="/imp1:registrarCompraEntrada/imp1:compra/orden/total">
              <total>
                <xsl:value-of select="/imp1:registrarCompraEntrada/imp1:compra/orden/total"/>
              </total>
            </xsl:if>
            <xsl:if test="/imp1:registrarCompraEntrada/imp1:compra/orden/cliente">
              <cliente>
                <xsl:if test="/imp1:registrarCompraEntrada/imp1:compra/orden/cliente/nombreUsuario">
                  <nombreUsuario>
                    <xsl:value-of select="/imp1:registrarCompraEntrada/imp1:compra/orden/cliente/nombreUsuario"/>
                  </nombreUsuario>
                </xsl:if>
                <xsl:if test="/imp1:registrarCompraEntrada/imp1:compra/orden/cliente/nombre">
                  <nombre>
                    <xsl:value-of select="/imp1:registrarCompraEntrada/imp1:compra/orden/cliente/nombre"/>
                  </nombre>
                </xsl:if>
                <xsl:if test="/imp1:registrarCompraEntrada/imp1:compra/orden/cliente/apellido">
                  <apellido>
                    <xsl:value-of select="/imp1:registrarCompraEntrada/imp1:compra/orden/cliente/apellido"/>
                  </apellido>
                </xsl:if>
                <xsl:if test="/imp1:registrarCompraEntrada/imp1:compra/orden/cliente/tipoDocumento">
                  <tipoDocumento>
                    <xsl:value-of select="/imp1:registrarCompraEntrada/imp1:compra/orden/cliente/tipoDocumento"/>
                  </tipoDocumento>
                </xsl:if>
                <xsl:if test="/imp1:registrarCompraEntrada/imp1:compra/orden/cliente/numeroDocumento">
                  <numeroDocumento>
                    <xsl:value-of select="/imp1:registrarCompraEntrada/imp1:compra/orden/cliente/numeroDocumento"/>
                  </numeroDocumento>
                </xsl:if>
                <xsl:if test="/imp1:registrarCompraEntrada/imp1:compra/orden/cliente/correoElectronico">
                  <correoElectronico>
                    <xsl:value-of select="/imp1:registrarCompraEntrada/imp1:compra/orden/cliente/correoElectronico"/>
                  </correoElectronico>
                </xsl:if>
                <xsl:if test="/imp1:registrarCompraEntrada/imp1:compra/orden/cliente/telefono">
                  <telefono>
                    <xsl:value-of select="/imp1:registrarCompraEntrada/imp1:compra/orden/cliente/telefono"/>
                  </telefono>
                </xsl:if>
                <xsl:if test="/imp1:registrarCompraEntrada/imp1:compra/orden/cliente/direccion">
                  <direccion>
                    <xsl:if test="/imp1:registrarCompraEntrada/imp1:compra/orden/cliente/direccion/numero">
                      <numero>
                        <xsl:value-of select="/imp1:registrarCompraEntrada/imp1:compra/orden/cliente/direccion/numero"/>
                      </numero>
                    </xsl:if>
                    <xsl:if test="/imp1:registrarCompraEntrada/imp1:compra/orden/cliente/direccion/ciudad">
                      <ciudad>
                        <xsl:value-of select="/imp1:registrarCompraEntrada/imp1:compra/orden/cliente/direccion/ciudad"/>
                      </ciudad>
                    </xsl:if>
                    <xsl:if test="/imp1:registrarCompraEntrada/imp1:compra/orden/cliente/direccion/departamento">
                      <departamento>
                        <xsl:value-of select="/imp1:registrarCompraEntrada/imp1:compra/orden/cliente/direccion/departamento"/>
                      </departamento>
                    </xsl:if>
                    <idCiudad>
                      <xsl:value-of select="/imp1:registrarCompraEntrada/imp1:compra/orden/cliente/direccion/idCiudad"/>
                    </idCiudad>
                    <idDepartamento>
                      <xsl:value-of select="/imp1:registrarCompraEntrada/imp1:compra/orden/cliente/direccion/idDepartamento"/>
                    </idDepartamento>
                  </direccion>
                </xsl:if>
              </cliente>
            </xsl:if>
            <xsl:if test="/imp1:registrarCompraEntrada/imp1:compra/orden/listaItems">
              <listaItems>
                <xsl:for-each select="/imp1:registrarCompraEntrada/imp1:compra/orden/listaItems/items">
                  <items>
                    <cantidad>
                      <xsl:value-of select="cantidad"/>
                    </cantidad>
                    <tipo>
                      <xsl:value-of select="tipo"/>
                    </tipo>
                    <xsl:if test="idCampania">
                      <idCampania>
                        <xsl:value-of select="idCampania"/>
                      </idCampania>
                    </xsl:if>
                    <producto>
                      <xsl:if test="producto/idProducto">
                        <idProducto>
                          <xsl:value-of select="producto/idProducto"/>
                        </idProducto>
                      </xsl:if>
                      <xsl:if test="producto/codigoProducto">
                        <codigoProducto>
                          <xsl:value-of select="producto/codigoProducto"/>
                        </codigoProducto>
                      </xsl:if>
                      <xsl:if test="producto/nombreProducto">
                        <nombreProducto>
                          <xsl:value-of select="producto/nombreProducto"/>
                        </nombreProducto>
                      </xsl:if>
                      <xsl:if test="producto/descripcionProducto">
                        <descripcionProducto>
                          <xsl:value-of select="producto/descripcionProducto"/>
                        </descripcionProducto>
                      </xsl:if>
                      <xsl:if test="producto/fabricanteProducto">
                        <fabricanteProducto>
                          <xsl:value-of select="producto/fabricanteProducto"/>
                        </fabricanteProducto>
                      </xsl:if>
                      <xsl:if test="producto/nombreImagenProducto">
                        <nombreImagenProducto>
                          <xsl:value-of select="producto/nombreImagenProducto"/>
                        </nombreImagenProducto>
                      </xsl:if>
                      <xsl:if test="producto/precioProducto">
                        <precioProducto>
                          <xsl:value-of select="producto/precioProducto"/>
                        </precioProducto>
                      </xsl:if>
                      <tipoProducto>
                        <categoria>
                          <xsl:if test="producto/tipoProducto/categoria/idTipo">
                            <idTipo>
                              <xsl:value-of select="producto/tipoProducto/categoria/idTipo"/>
                            </idTipo>
                          </xsl:if>
                          <xsl:if test="producto/tipoProducto/categoria/nombreTipo">
                            <nombreTipo>
                              <xsl:value-of select="producto/tipoProducto/categoria/nombreTipo"/>
                            </nombreTipo>
                          </xsl:if>
                        </categoria>
                        <subCategoria>
                          <xsl:if test="producto/tipoProducto/subCategoria/idTipo">
                            <idTipo>
                              <xsl:value-of select="producto/tipoProducto/subCategoria/idTipo"/>
                            </idTipo>
                          </xsl:if>
                          <xsl:if test="producto/tipoProducto/subCategoria/nombreTipo">
                            <nombreTipo>
                              <xsl:value-of select="producto/tipoProducto/subCategoria/nombreTipo"/>
                            </nombreTipo>
                          </xsl:if>
                        </subCategoria>
                      </tipoProducto>
                    </producto>
                  </items>
                </xsl:for-each>
              </listaItems>
            </xsl:if>
          </orden>
        </xsl:if>
      </imp1:compra>
    </imp1:registrarCompraEntrada>
  </xsl:template>
</xsl:stylesheet>
