<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../BPELOrdenCompra.wsdl"/>
      <rootElement name="registrarCompraEntrada" namespace="http://www.kallsony.com/operacion/registrarcompra"/>
    </source>
    <source type="WSDL">
      <schema location="../BPELOrdenCompra.wsdl"/>
      <rootElement name="ValidarDestinoSalida" namespace="http://www.kallsony.com.destino"/>
      <param name="VariableValidarDestinoSalida" />
    </source>
    <source type="WSDL">
      <schema location="http://DiegoPC:8001/soa-infra/services/default/ProjectGuardarOrden/BPELGuardarCompra.wsdl"/>
      <rootElement name="guardarCompraSalida" namespace="http://www.kallsony.com/operacion/guardarcompra"/>
      <param name="Invoke_guardarCompra_OutputVariable.payload" />
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="http://localhost:8001/soa-infra/services/default/ProjectEnvio/BPELEnvio.wsdl"/>
      <rootElement name="enviarCompraEntrada" namespace="http://www.kallsony.com/operacion/enviarcompra"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 140919.1004.0161) AT [TUE JUN 02 09:29:47 COT 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns3="http://www.kallsonys.com"
                xmlns:ns0="http://www.kallsony.com/entidad/compra"
                xmlns:ns6="http://www.kallsony.com/entidad/tarjeta"
                xmlns:ns11="http://kallsony.com/guardarcompra"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:ns13="http://xmlns.oracle.com/Appkallsonys/ProjectEnvio/BPELEnvio"
                xmlns:ns5="http://www.kallsony.com.monto"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns4="http://www.kallsony.com.destino"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns9="http://www.kallsony.com/entidad/producto"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns12="http://www.kallsony.com/operacion/enviarcompra"
                xmlns:ns1="http://www.kallsony.com/operacion/registrarcompra"
                xmlns:client="http://xmlns.oracle.com/Appkallsonys/ProjectOrden/BPELOrdenCompra"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns2="http://www.kallsony.com/entidad/orden"
                xmlns:ns10="http://www.kallsony.com/operacion/guardarcompra"
                xmlns:ns7="http://www.kallsony.com/entidad/usuario"
                xmlns:fk="http://www.kallsony.com/util/falta"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns8="http://www.kallsony.com/entidad/direccion"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl ns3 ns0 ns6 ns11 ns5 plnk ns4 wsdl ns9 ns1 client ns2 ns10 ns7 fk ns8 xsd ns13 ns12 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:param name="VariableValidarDestinoSalida"/>
  <xsl:param name="Invoke_guardarCompra_OutputVariable.payload"/>
  <xsl:template match="/">
    <ns12:enviarCompraEntrada>
      <ns12:idOrden>
        <xsl:value-of select="$Invoke_guardarCompra_OutputVariable.payload/ns10:guardarCompraSalida/ns10:idPreOrden"/>
      </ns12:idOrden>
      <ns12:nombreEnvio>
        <xsl:value-of select="$VariableValidarDestinoSalida/ns4:ValidarDestinoSalida/ns4:nombreProveedor"/>
      </ns12:nombreEnvio>
      <ns12:usuarioEnvio>
        <idUsuario>
          <xsl:value-of select="/ns1:registrarCompraEntrada/ns1:compra/usuarioEnvio/idUsuario"/>
        </idUsuario>
        <nombreUsuario>
          <xsl:value-of select="/ns1:registrarCompraEntrada/ns1:compra/usuarioEnvio/nombreUsuario"/>
        </nombreUsuario>
        <nombre>
          <xsl:value-of select="/ns1:registrarCompraEntrada/ns1:compra/usuarioEnvio/nombre"/>
        </nombre>
        <apellido>
          <xsl:value-of select="/ns1:registrarCompraEntrada/ns1:compra/usuarioEnvio/apellido"/>
        </apellido>
        <tipoDocumento>
          <xsl:value-of select="/ns1:registrarCompraEntrada/ns1:compra/usuarioEnvio/tipoDocumento"/>
        </tipoDocumento>
        <numeroDocumento>
          <xsl:value-of select="/ns1:registrarCompraEntrada/ns1:compra/usuarioEnvio/numeroDocumento"/>
        </numeroDocumento>
        <correoElectronico>
          <xsl:value-of select="/ns1:registrarCompraEntrada/ns1:compra/usuarioEnvio/correoElectronico"/>
        </correoElectronico>
        <telefono>
          <xsl:value-of select="/ns1:registrarCompraEntrada/ns1:compra/usuarioEnvio/telefono"/>
        </telefono>
        <direccion>
          <idDireccion>
            <xsl:value-of select="/ns1:registrarCompraEntrada/ns1:compra/usuarioEnvio/direccion/idDireccion"/>
          </idDireccion>
          <numero>
            <xsl:value-of select="/ns1:registrarCompraEntrada/ns1:compra/usuarioEnvio/direccion/numero"/>
          </numero>
          <ciudad>
            <xsl:value-of select="/ns1:registrarCompraEntrada/ns1:compra/usuarioEnvio/direccion/ciudad"/>
          </ciudad>
          <departamento>
            <xsl:value-of select="/ns1:registrarCompraEntrada/ns1:compra/usuarioEnvio/direccion/departamento"/>
          </departamento>
          <idCiudad>
            <xsl:value-of select="/ns1:registrarCompraEntrada/ns1:compra/usuarioEnvio/direccion/idCiudad"/>
          </idCiudad>
          <idDepartamento>
            <xsl:value-of select="/ns1:registrarCompraEntrada/ns1:compra/usuarioEnvio/direccion/idDepartamento"/>
          </idDepartamento>
          <idPais>
            <xsl:value-of select="/ns1:registrarCompraEntrada/ns1:compra/usuarioEnvio/direccion/idPais"/>
          </idPais>
          <pais>
            <xsl:value-of select="/ns1:registrarCompraEntrada/ns1:compra/usuarioEnvio/direccion/pais"/>
          </pais>
        </direccion>
        <idCategoria>
          <xsl:value-of select="/ns1:registrarCompraEntrada/ns1:compra/usuarioEnvio/idCategoria"/>
        </idCategoria>
        <internacional>
          <xsl:value-of select="/ns1:registrarCompraEntrada/ns1:compra/usuarioEnvio/internacional"/>
        </internacional>
      </ns12:usuarioEnvio>
      <ns12:orden>
        <idOrden>
          <xsl:value-of select="/ns1:registrarCompraEntrada/ns1:compra/orden/idOrden"/>
        </idOrden>
        <fechaOrden>
          <xsl:value-of select="/ns1:registrarCompraEntrada/ns1:compra/orden/fechaOrden"/>
        </fechaOrden>
        <estadoOrden>
          <xsl:value-of select="/ns1:registrarCompraEntrada/ns1:compra/orden/estadoOrden"/>
        </estadoOrden>
        <idEstadoOrden>
          <xsl:value-of select="/ns1:registrarCompraEntrada/ns1:compra/orden/idEstadoOrden"/>
        </idEstadoOrden>
        <numeroItems>
          <xsl:value-of select="/ns1:registrarCompraEntrada/ns1:compra/orden/numeroItems"/>
        </numeroItems>
        <total>
          <xsl:value-of select="/ns1:registrarCompraEntrada/ns1:compra/orden/total"/>
        </total>
        <cliente>
          <idUsuario>
            <xsl:value-of select="/ns1:registrarCompraEntrada/ns1:compra/orden/cliente/idUsuario"/>
          </idUsuario>
          <nombreUsuario>
            <xsl:value-of select="/ns1:registrarCompraEntrada/ns1:compra/orden/cliente/nombreUsuario"/>
          </nombreUsuario>
          <nombre>
            <xsl:value-of select="/ns1:registrarCompraEntrada/ns1:compra/orden/cliente/nombre"/>
          </nombre>
          <apellido>
            <xsl:value-of select="/ns1:registrarCompraEntrada/ns1:compra/orden/cliente/apellido"/>
          </apellido>
          <tipoDocumento>
            <xsl:value-of select="/ns1:registrarCompraEntrada/ns1:compra/orden/cliente/tipoDocumento"/>
          </tipoDocumento>
          <numeroDocumento>
            <xsl:value-of select="/ns1:registrarCompraEntrada/ns1:compra/orden/cliente/numeroDocumento"/>
          </numeroDocumento>
          <correoElectronico>
            <xsl:value-of select="/ns1:registrarCompraEntrada/ns1:compra/orden/cliente/correoElectronico"/>
          </correoElectronico>
          <telefono>
            <xsl:value-of select="/ns1:registrarCompraEntrada/ns1:compra/orden/cliente/telefono"/>
          </telefono>
          <xsl:if test="/ns1:registrarCompraEntrada/ns1:compra/orden/cliente/direccion">
            <direccion>
              <xsl:if test="/ns1:registrarCompraEntrada/ns1:compra/orden/cliente/direccion/idDireccion">
                <idDireccion>
                  <xsl:value-of select="/ns1:registrarCompraEntrada/ns1:compra/orden/cliente/direccion/idDireccion"/>
                </idDireccion>
              </xsl:if>
              <xsl:if test="/ns1:registrarCompraEntrada/ns1:compra/orden/cliente/direccion/numero">
                <numero>
                  <xsl:value-of select="/ns1:registrarCompraEntrada/ns1:compra/orden/cliente/direccion/numero"/>
                </numero>
              </xsl:if>
              <xsl:if test="/ns1:registrarCompraEntrada/ns1:compra/orden/cliente/direccion/ciudad">
                <ciudad>
                  <xsl:value-of select="/ns1:registrarCompraEntrada/ns1:compra/orden/cliente/direccion/ciudad"/>
                </ciudad>
              </xsl:if>
              <xsl:if test="/ns1:registrarCompraEntrada/ns1:compra/orden/cliente/direccion/departamento">
                <departamento>
                  <xsl:value-of select="/ns1:registrarCompraEntrada/ns1:compra/orden/cliente/direccion/departamento"/>
                </departamento>
              </xsl:if>
              <idCiudad>
                <xsl:value-of select="/ns1:registrarCompraEntrada/ns1:compra/orden/cliente/direccion/idCiudad"/>
              </idCiudad>
              <idDepartamento>
                <xsl:value-of select="/ns1:registrarCompraEntrada/ns1:compra/orden/cliente/direccion/idDepartamento"/>
              </idDepartamento>
              <idPais>
                <xsl:value-of select="/ns1:registrarCompraEntrada/ns1:compra/orden/cliente/direccion/idPais"/>
              </idPais>
              <pais>
                <xsl:value-of select="/ns1:registrarCompraEntrada/ns1:compra/orden/cliente/direccion/pais"/>
              </pais>
            </direccion>
          </xsl:if>
          <idCategoria>
            <xsl:value-of select="/ns1:registrarCompraEntrada/ns1:compra/orden/cliente/idCategoria"/>
          </idCategoria>
          <internacional>
            <xsl:value-of select="/ns1:registrarCompraEntrada/ns1:compra/orden/cliente/internacional"/>
          </internacional>
        </cliente>
        <xsl:if test="/ns1:registrarCompraEntrada/ns1:compra/orden/listaItems">
          <listaItems>
            <xsl:for-each select="/ns1:registrarCompraEntrada/ns1:compra/orden/listaItems/items">
              <items>
                <cantidad>
                  <xsl:value-of select="cantidad"/>
                </cantidad>
                <tipo>
                  <xsl:value-of select="tipo"/>
                </tipo>
                <xsl:if test="idCampania">
                  <idCampania>
                    <xsl:value-of select="idCampania"/>
                  </idCampania>
                </xsl:if>
                <producto>
                  <xsl:if test="producto/idProducto">
                    <idProducto>
                      <xsl:value-of select="producto/idProducto"/>
                    </idProducto>
                  </xsl:if>
                  <xsl:if test="producto/codigoProducto">
                    <codigoProducto>
                      <xsl:value-of select="producto/codigoProducto"/>
                    </codigoProducto>
                  </xsl:if>
                  <xsl:if test="producto/nombreProducto">
                    <nombreProducto>
                      <xsl:value-of select="producto/nombreProducto"/>
                    </nombreProducto>
                  </xsl:if>
                  <xsl:if test="producto/descripcionProducto">
                    <descripcionProducto>
                      <xsl:value-of select="producto/descripcionProducto"/>
                    </descripcionProducto>
                  </xsl:if>
                  <xsl:if test="producto/fabricanteProducto">
                    <fabricanteProducto>
                      <xsl:value-of select="producto/fabricanteProducto"/>
                    </fabricanteProducto>
                  </xsl:if>
                  <xsl:if test="producto/nombreImagenProducto">
                    <nombreImagenProducto>
                      <xsl:value-of select="producto/nombreImagenProducto"/>
                    </nombreImagenProducto>
                  </xsl:if>
                  <xsl:if test="producto/precioProducto">
                    <precioProducto>
                      <xsl:value-of select="producto/precioProducto"/>
                    </precioProducto>
                  </xsl:if>
                  <tipoProducto>
                    <categoria>
                      <xsl:if test="producto/tipoProducto/categoria/idTipo">
                        <idTipo>
                          <xsl:value-of select="producto/tipoProducto/categoria/idTipo"/>
                        </idTipo>
                      </xsl:if>
                      <xsl:if test="producto/tipoProducto/categoria/nombreTipo">
                        <nombreTipo>
                          <xsl:value-of select="producto/tipoProducto/categoria/nombreTipo"/>
                        </nombreTipo>
                      </xsl:if>
                    </categoria>
                    <subCategoria>
                      <xsl:if test="producto/tipoProducto/subCategoria/idTipo">
                        <idTipo>
                          <xsl:value-of select="producto/tipoProducto/subCategoria/idTipo"/>
                        </idTipo>
                      </xsl:if>
                      <xsl:if test="producto/tipoProducto/subCategoria/nombreTipo">
                        <nombreTipo>
                          <xsl:value-of select="producto/tipoProducto/subCategoria/nombreTipo"/>
                        </nombreTipo>
                      </xsl:if>
                    </subCategoria>
                  </tipoProducto>
                </producto>
              </items>
            </xsl:for-each>
          </listaItems>
        </xsl:if>
      </ns12:orden>
    </ns12:enviarCompraEntrada>
  </xsl:template>
</xsl:stylesheet>
