<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../BPELOrdenCompra.wsdl"/>
      <rootElement name="unItem" namespace="http://www.kallsony.com/entidad/orden"/>
    </source>
    <source type="WSDL">
      <schema location="../setOrden.wsdl"/>
      <rootElement name="OrdenCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/setOrden"/>
      <param name="InvokeSetOrden_OutputVariable.OrdenCollection" />
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../setItemOrden.wsdl"/>
      <rootElement name="ItemOrdenCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/setItemOrden"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 140919.1004.0161) AT [MON APR 20 17:34:14 COT 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns3="http://www.kallsony.com/entidad/compra"
                xmlns:ns5="http://www.kallsony.com/entidad/tarjeta"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:ns7="http://xmlns.oracle.com/pcbpel/adapter/db/Appkallsonys/ProjectOrden/setItemOrden"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ns4="http://www.kallsony.com/entidad/producto"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns1="http://www.kallsony.com/operacion/registrarcompra"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/setOrden"
                xmlns:client="http://xmlns.oracle.com/Appkallsonys/ProjectOrden/BPELOrdenCompra"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Appkallsonys/ProjectOrden/setOrden"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns2="http://www.kallsony.com/entidad/orden"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns6="http://www.kallsony.com/entidad/usuario"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns0="http://www.kallsony.com/entidad/direccion"
                xmlns:ns8="http://xmlns.oracle.com/pcbpel/adapter/db/top/setItemOrden"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl ns3 ns5 plnk wsdl ns4 ns1 top client tns ns2 ns6 ns0 xsd ns7 ns8 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:param name="InvokeSetOrden_OutputVariable.OrdenCollection"/>
  <xsl:template match="/">
    <ns8:ItemOrdenCollection>
      <ns8:ItemOrden>
        <xsl:if test="/ns2:unItem/tipo">
          <xsl:choose>
            <xsl:when test=" string(/ns2:unItem/tipo) ='true'">
              <ns8:tipoitem>
                <xsl:value-of select="number(1)"/>
              </ns8:tipoitem>
            </xsl:when>
            <xsl:otherwise>
              <ns8:tipoitem>
                <xsl:value-of select="number(0)"/>
              </ns8:tipoitem>
            </xsl:otherwise>
          </xsl:choose>
        </xsl:if>
        <xsl:if test="$InvokeSetOrden_OutputVariable.OrdenCollection/top:OrdenCollection/top:Orden/top:idorden">
          <ns8:idorden>
            <xsl:value-of select="$InvokeSetOrden_OutputVariable.OrdenCollection/top:OrdenCollection/top:Orden/top:idorden"/>
          </ns8:idorden>
        </xsl:if>
        <xsl:if test="/ns2:unItem/producto/idProducto">
          <ns8:idproducto>
            <xsl:value-of select="/ns2:unItem/producto/idProducto"/>
          </ns8:idproducto>
        </xsl:if>
        <xsl:if test="/ns2:unItem/producto/codigoProducto">
          <ns8:codigoproducto>
            <xsl:value-of select="/ns2:unItem/producto/codigoProducto"/>
          </ns8:codigoproducto>
        </xsl:if>
        <xsl:if test="/ns2:unItem/producto/nombreProducto">
          <ns8:nombreproducto>
            <xsl:value-of select="/ns2:unItem/producto/nombreProducto"/>
          </ns8:nombreproducto>
        </xsl:if>
        <xsl:if test="/ns2:unItem/cantidad">
          <ns8:cantidaditem>
            <xsl:value-of select="/ns2:unItem/cantidad"/>
          </ns8:cantidaditem>
        </xsl:if>
        <xsl:if test="/ns2:unItem/producto/precioProducto">
          <ns8:valorunitarioitem>
            <xsl:value-of select="/ns2:unItem/producto/precioProducto"/>
          </ns8:valorunitarioitem>
        </xsl:if>
      </ns8:ItemOrden>
    </ns8:ItemOrdenCollection>
  </xsl:template>
</xsl:stylesheet>
