<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../getUsuario.wsdl"/>
      <rootElement name="UsuarioCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/getUsuario"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../BPELOrdenCompra.wsdl"/>
      <rootElement name="unUsuario" namespace="http://www.kallsony.com/entidad/orden"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 140919.1004.0161) AT [WED APR 22 10:21:17 COT 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:ns7="http://www.kallsonys.com"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns3="http://www.kallsony.com/entidad/compra"
                xmlns:ns5="http://www.kallsony.com/entidad/tarjeta"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns8="http://www.kallsony.com.destino"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ns4="http://www.kallsony.com/entidad/producto"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns1="http://www.kallsony.com/operacion/registrarcompra"
                xmlns:client="http://xmlns.oracle.com/Appkallsonys/ProjectOrden/BPELOrdenCompra"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns2="http://www.kallsony.com/entidad/orden"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns6="http://www.kallsony.com/entidad/usuario"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns0="http://www.kallsony.com/entidad/direccion"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/getUsuario"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Appkallsonys/ProjectOrden/getUsuario"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl plt wsdl xsd top tns ns7 ns3 ns5 ns8 ns4 ns1 client ns2 ns6 ns0 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <ns2:unUsuario>
      <xsl:if test="/top:UsuarioCollection/top:Usuario/top:idusuario">
        <idUsuario>
          <xsl:value-of select="/top:UsuarioCollection/top:Usuario/top:idusuario"/>
        </idUsuario>
      </xsl:if>
      <xsl:if test="/top:UsuarioCollection/top:Usuario/top:username">
        <nombreUsuario>
          <xsl:value-of select="/top:UsuarioCollection/top:Usuario/top:username"/>
        </nombreUsuario>
      </xsl:if>
      <xsl:if test="/top:UsuarioCollection/top:Usuario/top:nombres">
        <nombre>
          <xsl:value-of select="/top:UsuarioCollection/top:Usuario/top:nombres"/>
        </nombre>
      </xsl:if>
      <xsl:if test="/top:UsuarioCollection/top:Usuario/top:apellidos">
        <apellido>
          <xsl:value-of select="/top:UsuarioCollection/top:Usuario/top:apellidos"/>
        </apellido>
      </xsl:if>
      <xsl:if test="/top:UsuarioCollection/top:Usuario/top:tipodocumento">
        <tipoDocumento>
          <xsl:value-of select="/top:UsuarioCollection/top:Usuario/top:tipodocumento"/>
        </tipoDocumento>
      </xsl:if>
      <xsl:if test="/top:UsuarioCollection/top:Usuario/top:numerodocumento">
        <numeroDocumento>
          <xsl:value-of select="/top:UsuarioCollection/top:Usuario/top:numerodocumento"/>
        </numeroDocumento>
      </xsl:if>
      <xsl:if test="/top:UsuarioCollection/top:Usuario/top:email">
        <correoElectronico>
          <xsl:value-of select="/top:UsuarioCollection/top:Usuario/top:email"/>
        </correoElectronico>
      </xsl:if>
      <xsl:if test="/top:UsuarioCollection/top:Usuario/top:telefono">
        <telefono>
          <xsl:value-of select="/top:UsuarioCollection/top:Usuario/top:telefono"/>
        </telefono>
      </xsl:if>
      <direccion>
        <xsl:if test="/top:UsuarioCollection/top:Usuario/top:iddireccion">
          <idDireccion>
            <xsl:value-of select="/top:UsuarioCollection/top:Usuario/top:iddireccion"/>
          </idDireccion>
        </xsl:if>
      </direccion>
      <xsl:if test="/top:UsuarioCollection/top:Usuario/top:idcategoria">
        <idCategoria>
          <xsl:value-of select="/top:UsuarioCollection/top:Usuario/top:idcategoria"/>
        </idCategoria>
      </xsl:if>
      <internacional>
        <xsl:value-of select='number(/top:UsuarioCollection/top:Usuario/top:compraencolombia) = number("1")'/>
      </internacional>
    </ns2:unUsuario>
  </xsl:template>
</xsl:stylesheet>
