USE PRODUCTOSxxx
go
insert into producto.producto values('MIC_LG_01','Horno Microondas LG 0.8 Pies', 'Horno Microondas LG 0.8 Pies', 'LG','MICRO001.png',3,67200)
insert into producto.producto values('MIC_OST_01','Horno microondas OSTER Negro 9 Litros', 'Horno microondas OSTER Negro 9 Litros', 'OSTER','MICRO002.png',3,67700)
insert into producto.producto values('MIC_OST_02','Horno microondas OSTER Gourmet Collection', 'Horno microondas OSTER Gourmet Collection', 'OSTER','MICRO003.png',3,68200)
insert into producto.producto values('MIC_OST_03','Horno microondas OSTER 15 Litros Rojo', 'Horno microondas OSTER 15 Litros Rojo', 'OSTER','MICRO004.png',3,68700)
insert into producto.producto values('MIC_HAC_01','Horno Microondas HACEB Grill Inox', 'Horno Microondas HACEB Grill Inox', 'HACEB','MICRO005.png',3,69200)
insert into producto.producto values('MIC_LG_02','Horno Microondas LG 1.1 Pies', 'Horno Microondas LG 1.1 Pies', 'LG','MICRO006.png',3,69700)
insert into producto.producto values('MIC_SAM_01','Horno Microondas SAMSUNG 0.8', 'Horno Microondas SAMSUNG 0.8', 'SAMSUNG','MICRO007.png',3,70200)
insert into producto.producto values('MIC_LG_03','Horno Microondas LG 0.8 Pc Acabdo', 'Horno Microondas LG 0.8 Pc Acabdo', 'LG','MICRO008.png',3,70700)
insert into producto.producto values('MIC_LG_04','Horno Microondas LG 1.4 Pc Acabado', 'Horno Microondas LG 1.4 Pc Acabado', 'LG','MICRO009.png',3,71200)
insert into producto.producto values('MIC_WHI_01','Horno Microondas WHIRLPOOL  1.1 Pies C bl', 'Horno Microondas WHIRLPOOL  1.1 Pies C bl', 'WHIRPOOL','MICRO010.png',3,71700)
insert into producto.producto values('MIC_SIM_01','Horno Microondas SIMPLY 0.7 Pc Metali', 'Horno Microondas SIMPLY 0.7 Pc Metali', 'SIMPLY','MICRO011.png',3,72200)
insert into producto.producto values('MIC_LG_05','Horno Microondas LG 0.7 Pc Acero', 'Horno Microondas LG 0.7 Pc Acero', 'LG','MICRO012.png',3,72700)
insert into producto.producto values('MIC_WHI_02','Horno Microondas WHIRLPOOL 0.7 Pies + Easy Pot', 'Horno Microondas WHIRLPOOL 0.7 Pies + Easy Pot', 'WHIRPOOL','MICRO013.png',3,73200)
insert into producto.producto values('MIC_HAC_02','Horno Microondas HACEB 0.7 Pc Inox', 'Horno Microondas HACEB 0.7 Pc Inox', 'HACEB','MICRO014.png',3,73700)
insert into producto.producto values('MIC_HAC_03','Horno Microondas HACEB 0.7 Pc Bco', 'Horno Microondas HACEB 0.7 Pc Bco', 'HACEB','MICRO015.png',3,74200)
insert into producto.producto values('MIC_HAC_04','Horno Microondas HACEB Arezzo 0.7 pc', 'Horno Microondas HACEB Arezzo 0.7 pc', 'HACEB','MICRO016.png',3,74700)
insert into producto.producto values('MIC_SIM_02','Horno Microondas SIMPLY 0.7 Pc Blanco', 'Horno Microondas SIMPLY 0.7 Pc Blanco', 'SIMPLY','MICRO017.png',3,75200)
insert into producto.producto values('MIC_ELE_01','Microondas ELECTROLUX EMDL170.7', 'Microondas ELECTROLUX EMDL170.7', 'ELECTROLUX','MICRO018.png',3,75700)
insert into producto.producto values('MIC_KAL_01','Horno Microondas 0.7" KALLEY K-MW700 Blanco', 'Horno Microondas 0.7" KALLEY K-MW700 Blanco', 'KALLEY','MICRO019.png',3,76200)
insert into producto.producto values('MIC_KAL_02','Horno Microondas 0.7" KALLEY K-MW700 Negro', 'Horno Microondas 0.7" KALLEY K-MW700 Negro', 'KALLEY','MICRO020.png',3,76700)
insert into producto.producto values('MIC_WHI_03','Horno Microondas WHIRLPOOL WMS07ZWHS Blanco', 'Horno Microondas WHIRLPOOL WMS07ZWHS Blanco', 'WHIRPOOL','MICRO021.png',3,77200)
insert into producto.producto values('MIC_SAM_02','Horno Microondas SAMSUNG 0.8AMW831K', 'Horno Microondas SAMSUNG 0.8AMW831K', 'SAMSUNG','MICRO022.png',3,77700)
go
