USE PRODUCTOSxxx
GO
insert into producto.producto values('EST_HAC_01','Estufa HACEB Asl -V76 Gn Pl 6 Puesto', 'Estufa HACEB Asl -V76 Gn Pl 6 Puesto', 'HACEB','ESTUFA001.png',4,544800)
insert into producto.producto values('EST_HAC_02','Estufa HACEB 4 Puestos AsL-V60 Gn in', 'Estufa HACEB 4 Puestos AsL-V60 Gn in', 'HACEB','ESTUFA002.png',4,545700)
insert into producto.producto values('EST_HAC_03','Estufa HACEB  4 Puestos Vs Negra', 'Estufa HACEB  4 Puestos Vs Negra', 'HACEB','ESTUFA003.png',4,546600)
insert into producto.producto values('EST_HAC_04','Estufa HACEB  4 Puestos Arl Gratinado', 'Estufa HACEB  4 Puestos Arl Gratinado', 'HACEB','ESTUFA004.png',4,547500)
insert into producto.producto values('EST_HAC_05','Estufa HACEB 4 puestos arezo espalda', 'Estufa HACEB 4 puestos arezo espalda', 'HACEB','ESTUFA005.png',4,548400)
insert into producto.producto values('EST_HAC_06','Estufa HACEB 4 Pto AR-V Gabinete gn', 'Estufa HACEB 4 Pto AR-V Gabinete gn', 'HACEB','ESTUFA006.png',4,549300)
insert into producto.producto values('EST_ABB_01','Estufa de Mesa ABBA 4P SG4001 A Gas Propano', 'Estufa de Mesa ABBA 4P SG4001 A Gas Propano', 'ABBA','ESTUFA007.png',4,550200)
insert into producto.producto values('EST_ABB_02','Estufa de Mesa ABBA 4P SG4005N A Gas Natural', 'Estufa de Mesa ABBA 4P SG4005N A Gas Natural', 'ABBA','ESTUFA008.png',4,551100)
insert into producto.producto values('EST_ABB_03','Estufa ABBA 20 AB1001N A Gas Natural', 'Estufa ABBA 20 AB1001N A Gas Natural', 'ABBA','ESTUFA009.png',4,552000)
insert into producto.producto values('EST_SUP_01','Estufa de piso SUPERIOR 20 SN701608 GNV Negro', 'Estufa de piso SUPERIOR 20 SN701608 GNV Negro', 'SUPERIOR','ESTUFA010.png',4,552900)
insert into producto.producto values('EST_ICA_01','Estufa ICASA GVI20EEGN GRT NE Negro', 'Estufa ICASA GVI20EEGN GRT NE Negro', 'ICASA','ESTUFA011.png',4,553800)
insert into producto.producto values('EST_SUP_02','Estufa SUPERIOR SN-GOLD-T GP Negra', 'Estufa SUPERIOR SN-GOLD-T GP Negra', 'SUPERIOR','ESTUFA012.png',4,554700)
insert into producto.producto values('EST_SUP_03','Estufa de Piso SUPERIOR SG-TITANIUM Gas Natural', 'Estufa de Piso SUPERIOR SG-TITANIUM Gas Natural', 'SUPERIOR','ESTUFA013.png',4,555600)
insert into producto.producto values('EST_CHA_01','Estufa CHALLENGER Cocina Autosoportada 4 puestos', 'Estufa CHALLENGER Cocina Autosoportada 4 Puestos Con Energía Eléctrica', 'CHALLENGER','ESTUFA014.png',4,556500)
insert into producto.producto values('EST_CHA_02','Estufa CHALLENGER  Cubierta Vidrio de Gas 5 Puestos Squadra', 'Estufa CHALLENGER  Cubierta Vidrio de Gas 5 Puestos Squadra', 'CHALLENGER','ESTUFA015.png',4,557400)
insert into producto.producto values('EST_CHA_03','Estufa CHALLENGER Cubierta Con Termopar Seguridad 4 Puestos', 'Estufa CHALLENGER Cubierta Con Termopar Seguridad 4 Puestos', 'CHALLENGER','ESTUFA016.png',4,558300)
insert into producto.producto values('EST_CHA_04','Estufa CHALLENGER Cubierta Vidrio Mixta 220 V Squadra', 'Estufa CHALLENGER Cubierta Vidrio Mixta 220 V Squadra', 'CHALLENGER','ESTUFA017.png',4,559200)
insert into producto.producto values('EST_GEN_01','Estufa GENERAL ELECTRIC Cubierta 4 puestos', 'Estufa GENERAL ELECTRIC Cubierta 4 puestos a gas natural panel en vidrio', 'CHALLENGER','ESTUFA018.png',4,560100)
insert into producto.producto values('EST_HAC_07','Estufa HACEB  de piso tapa de vidrio 4 puestos', 'Estufa HACEB  de piso tapa de vidrio 4 puestos a gas natural 50 cm', 'HACEB','ESTUFA019.png',4,561000)
insert into producto.producto values('EST_HAC_08','Estufa HACEB Cubierta 60 cm acero inoxidable gas natural', 'Estufa HACEB Cubierta 60 cm acero inoxidable gas natural', 'HACEB','ESTUFA020.png',4,561900)
insert into producto.producto values('EST_HAC_09','Estufa  HACEB sobremesa torre 4 puestos gas propano se negra', 'Estufa  HACEB sobremesa torre 4 puestos gas propano se negra', 'HACEB','ESTUFA021.png',4,562800)
go
