USE PRODUCTOSxxx
GO
insert into producto.producto values('LIC_01','Licuadora OSTER 1400 Watts Potencia', 'Licuadora OSTER 1400 Watts Potencia', 'OSTER','LICUADORA001.png',5,95600)
insert into producto.producto values('LIC_02','Licuadora OSTER Core 10 Vel Roja', 'Licuadora OSTER Core 10 Vel Roja', 'OSTER','LICUADORA002.png',5,98300)
insert into producto.producto values('LIC_03','Licuadora OSTER 12 Velocidades Core+', 'Licuadora OSTER 12 Velocidades Core+', 'OSTER','LICUADORA003.png',5,101000)
insert into producto.producto values('LIC_04','Licuadora OSTER Core Roja 450watts Vaso Vidrio', 'Licuadora OSTER Core Roja 450watts Vaso Vidrio', 'OSTER','LICUADORA004.png',5,103700)
insert into producto.producto values('LIC_05','Licuadora OSTER Reversible Gourmet ', 'Licuadora OSTER Reversible Gourmet ', 'OSTER','LICUADORA005.png',5,106400)
insert into producto.producto values('LIC_06','Licuadora HAMILTON BEACH 10 Velocidades', 'Licuadora HAMILTON BEACH 10 Velocidades', 'HAMILTON','LICUADORA006.png',5,109100)
insert into producto.producto values('LIC_07','Licuadora PREMIUM  4vel Negra Vasovidri', 'Licuadora PREMIUM  4vel Negra Vasovidri', 'PREMIUM','LICUADORA007.png',5,111800)
insert into producto.producto values('LIC_08','Licuadora ELECTROLUX Easy Line Negra', 'Licuadora ELECTROLUX Easy Line Negra', 'ELECTROLUX','LICUADORA008.png',5,114500)
insert into producto.producto values('LIC_09','Licuadora ELECTROLUX Chef', 'Licuadora ELECTROLUX Chef', 'ELECTROLUX','LICUADORA009.png',5,117200)
insert into producto.producto values('LIC_10','Licuadora IMUSA Faciclic 4vel Blanca', 'Licuadora IMUSA Faciclic 4vel Blanca', 'IMUSA','LICUADORA010.png',5,119900)
insert into producto.producto values('LIC_11','Licuadora  BLACK & DECKER 2 Vel Con Pulso', 'Licuadora  BLACK & DECKER 2 Vel Con Pulso', 'BLACK & DECKER','LICUADORA011.png',5,122600)
insert into producto.producto values('LIC_12','Licuadora BLACK & DECKER Fusionblade 4 Veloc', 'Licuadora BLACK & DECKER Fusionblade 4 Veloc', 'BLACK & DECKER','LICUADORA012.png',5,125300)
insert into producto.producto values('LIC_13','Licuadora IMUSA Faciclic 8vel Negra', 'Licuadora IMUSA Faciclic 8vel Negra', 'IMUSA','LICUADORA013.png',5,128000)
insert into producto.producto values('LIC_14','Licuadora IMUSA Faciclic Plus Negra', 'Licuadora IMUSA Faciclic Plus Negra', 'IMUSA','LICUADORA014.png',5,130700)
insert into producto.producto values('LIC_15','Licuadora OSTER 8 Velocidades Con va', 'Licuadora OSTER 8 Velocidades Con va', 'OSTER','LICUADORA015.png',5,133400)
insert into producto.producto values('LIC_16','Licuadora SAMURAI Optimix ', 'Licuadora SAMURAI Optimix ', 'SAMURAI','LICUADORA016.png',5,136100)
insert into producto.producto values('LIC_17','Licuadora IMUSA Properfect 10v Blan', 'Licuadora IMUSA Properfect 10v Blan', 'IMUSA','LICUADORA017.png',5,138800)
insert into producto.producto values('LIC_18','Licuadora HAMILTON BEACH Con Dispensador Ngra', 'Licuadora HAMILTON BEACH Con Dispensador Ngra', 'HAMILTON','LICUADORA018.png',5,141500)
insert into producto.producto values('LIC_19','Licuadora UNIVERSAL 3 Velocidades Negra', 'Licuadora UNIVERSAL 3 Velocidades Negra', 'UNIVERSAL','LICUADORA019.png',5,144200)
insert into producto.producto values('LIC_20','Licuadora OSTER BLSTDG', 'Licuadora OSTER BLSTDG', 'OSTER','LICUADORA020.png',5,146900)
insert into producto.producto values('LIC_21','Licuadora OSTER Cromada 3V 465-5', 'Licuadora OSTER Cromada 3V 465-5', 'OSTER','LICUADORA021.png',5,149600)
GO
