USE PRODUCTOSxxx
GO
insert into producto.producto values('PLA_01','Plancha Vapor SAMURAI Calore26', 'Plancha Vapor SAMURAI Calore26', 'SAMURAI','PLANCHA001.png',6,87400)
insert into producto.producto values('PLA_02','Plancha de Ropa B&D Vapor IR01P', 'Plancha de Ropa B&D Vapor IR01P', 'BLACK & DECKER','PLANCHA002.png',6,88100)
insert into producto.producto values('PLA_03','Plancha ELECTROLUX Vapor Fresh # 2', 'Plancha ELECTROLUX Vapor Fresh # 2', 'ELECTROLUX','PLANCHA003.png',6,88800)
insert into producto.producto values('PLA_04','Plancha Vapor B&D IRBD1001', 'Plancha Vapor B&D IRBD1001', 'BLACK & DECKER','PLANCHA004.png',6,89500)
insert into producto.producto values('PLA_05','Plancha ELECTROLUX A Vapor Arezza Azul', 'Plancha ELECTROLUX A Vapor Arezza Azul', 'ELECTROLUX','PLANCHA005.png',6,90200)
insert into producto.producto values('PLA_06','Plancha ELECTROLUX A Vapor Amethyst', 'Plancha ELECTROLUX A Vapor Amethyst', 'ELECTROLUX','PLANCHA006.png',6,90900)
insert into producto.producto values('PLA_07','Plancha de Ropa B&D Antihaderente IR02T', 'Plancha de Ropa B&D Antihaderente IR02T', 'BLACK & DECKER','PLANCHA007.png',6,91600)
insert into producto.producto values('PLA_08','Plancha SAMURAI Vapor Calore 26', 'Plancha SAMURAI Vapor Calore 26', 'SAMURAI','PLANCHA008.png',6,92300)
insert into producto.producto values('PLA_09','Plancha de Ropa B&D Extravapor IR1160S1', 'Plancha de Ropa B&D Extravapor IR1160S1', 'BLACK & DECKER','PLANCHA009.png',6,93000)
insert into producto.producto values('PLA_10','Plancha UNIVERSAL A Vapor Extra Liviana', 'Plancha UNIVERSAL A Vapor Extra Liviana', 'UNIVERSAL','PLANCHA010.png',6,93700)
insert into producto.producto values('PLA_11','Plancha SAMURAI Easycord', 'Plancha SAMURAI Easycord', 'SAMURAI','PLANCHA011.png',6,94400)
insert into producto.producto values('PLA_12','Plancha OSTER 7001 Autoapagado', 'Plancha OSTER 7001 Autoapagado', 'OSTER','PLANCHA012.png',6,95100)
insert into producto.producto values('PLA_13','Plancha BLACK & DECKER Vapor Vertical Antiadh', 'Plancha BLACK & DECKER Vapor Vertical Antiadh', 'BLACK & DECKER','PLANCHA013.png',6,95800)
insert into producto.producto values('PLA_14','Plancha BLACK & DECKER Vapor Suela Antiadhere', 'Plancha BLACK & DECKER Vapor Suela Antiadhere', 'BLACK & DECKER','PLANCHA014.png',6,96500)
insert into producto.producto values('PLA_15','Plancha SAMURAI Vapor Aquaspeed', 'Plancha SAMURAI Vapor Aquaspeed', 'SAMURAI','PLANCHA015.png',6,97200)
insert into producto.producto values('PLA_16','Plancha SAMURAI Vapor Virtuo', 'Plancha SAMURAI Vapor Virtuo', 'SAMURAI','PLANCHA016.png',6,97900)
insert into producto.producto values('PLA_17','Plancha OSTER Suela Tourmalina Iónic', 'Plancha OSTER Suela Tourmalina Iónic', 'OSTER','PLANCHA017.png',6,98600)
insert into producto.producto values('PLA_18','Plancha OSTER Suela Cerámica', 'Plancha OSTER Suela Cerámica', 'OSTER','PLANCHA018.png',6,99300)
insert into producto.producto values('PLA_19','Plancha OSTER Golpe Vapor Vertical', 'Plancha OSTER Golpe Vapor Vertical', 'OSTER','PLANCHA019.png',6,100000)
insert into producto.producto values('PLA_20','Plancha BLACK & DECKER Antiadherente Antigote', 'Plancha BLACK & DECKER Antiadherente Antigote', 'BLACK & DECKER','PLANCHA020.png',6,100700)
insert into producto.producto values('PLA_21','Plancha SAMURAI A Vapor Ultra Glide', 'Plancha SAMURAI A Vapor Ultra Glide', 'SAMURAI','PLANCHA021.png',6,101400)
GO
