<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../BPELEnvio.wsdl"/>
      <rootElement name="enviarCompraEntrada" namespace="http://www.kallsony.com/operacion/enviarcompra"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../setServientrega.wsdl"/>
      <rootElement name="KallsonysShipmentCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/setServientrega"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 140919.1004.0161) AT [TUE JUN 02 07:42:54 COT 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:client="http://xmlns.oracle.com/Appkallsonys/ProjectEnvio/BPELEnvio"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/setServientrega"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ns2="http://www.kallsony.com/entidad/producto"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns1="http://www.kallsony.com/operacion/enviarcompra"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Appkallsonys/ProjectEnvio/setServientrega"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns3="http://www.kallsony.com/entidad/orden"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns4="http://www.kallsony.com/entidad/usuario"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns0="http://www.kallsony.com/entidad/direccion"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl client plnk wsdl ns2 ns1 ns3 ns4 ns0 xsd top tns xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <top:KallsonysShipmentCollection>
      <top:KallsonysShipment>
        <top:orderid>
          <xsl:value-of select="/ns1:enviarCompraEntrada/ns1:idOrden"/>
        </top:orderid>
        <top:fname>
          <xsl:value-of select="/ns1:enviarCompraEntrada/ns1:usuarioEnvio/nombre"/>
        </top:fname>
        <top:lname>
          <xsl:value-of select="/ns1:enviarCompraEntrada/ns1:usuarioEnvio/apellido"/>
        </top:lname>
        <top:street>
          <xsl:value-of select="/ns1:enviarCompraEntrada/ns1:usuarioEnvio/direccion/numero"/>
        </top:street>
        <top:city>
          <xsl:value-of select="/ns1:enviarCompraEntrada/ns1:usuarioEnvio/direccion/idCiudad"/>
        </top:city>
        <top:state>
          <xsl:value-of select="/ns1:enviarCompraEntrada/ns1:usuarioEnvio/direccion/idDepartamento"/>
        </top:state>
        <top:zipcode>
          <xsl:value-of select='number("1")'/>
        </top:zipcode>
        <top:Estado>
          <xsl:value-of select='number("1")'/>
        </top:Estado>
      </top:KallsonysShipment>
    </top:KallsonysShipmentCollection>
  </xsl:template>
</xsl:stylesheet>
