<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../BPELGuardarCompra.wsdl"/>
      <rootElement name="guardarCompraEntrada" namespace="http://www.kallsony.com/operacion/guardarcompra"/>
    </source>
    <source type="WSDL">
      <schema location="../setOrden.wsdl"/>
      <rootElement name="OrdenCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/setOrden"/>
      <param name="InvokeSetOrden_OutputVariable.OrdenCollection" />
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../setEnvio.wsdl"/>
      <rootElement name="EnvioCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/setEnvio"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 140919.1004.0161) AT [SUN MAY 31 12:14:17 COT 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns2="http://www.kallsony.com/entidad/compra"
                xmlns:ns4="http://www.kallsony.com/entidad/tarjeta"
                xmlns:client="http://kallsony.com/guardarcompra"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns7="http://xmlns.oracle.com/pcbpel/adapter/db/Appkallsonys/ProjectGuardarOrden/setEnvio"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ns3="http://www.kallsony.com/entidad/producto"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/setOrden"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:ns8="http://xmlns.oracle.com/pcbpel/adapter/db/top/setEnvio"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Appkallsonys/ProjectGuardarOrden/setOrden"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns5="http://www.kallsony.com/entidad/orden"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns1="http://www.kallsony.com/operacion/guardarcompra"
                xmlns:ns6="http://www.kallsony.com/entidad/usuario"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns0="http://www.kallsony.com/entidad/direccion"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl ns2 ns4 client plnk wsdl ns3 top tns ns5 ns1 ns6 ns0 xsd ns7 ns8 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:param name="InvokeSetOrden_OutputVariable.OrdenCollection"/>
  <xsl:template match="/">
    <ns8:EnvioCollection>
      <ns8:Envio>
        <xsl:if test="$InvokeSetOrden_OutputVariable.OrdenCollection/top:OrdenCollection/top:Orden/top:idorden">
          <ns8:idorden>
            <xsl:value-of select="$InvokeSetOrden_OutputVariable.OrdenCollection/top:OrdenCollection/top:Orden/top:idorden"/>
          </ns8:idorden>
        </xsl:if>
        <xsl:if test="/ns1:guardarCompraEntrada/ns1:compra/usuarioEnvio/nombre">
          <ns8:nombres>
            <xsl:value-of select="/ns1:guardarCompraEntrada/ns1:compra/usuarioEnvio/nombre"/>
          </ns8:nombres>
        </xsl:if>
        <xsl:if test="/ns1:guardarCompraEntrada/ns1:compra/usuarioEnvio/apellido">
          <ns8:apellidos>
            <xsl:value-of select="/ns1:guardarCompraEntrada/ns1:compra/usuarioEnvio/apellido"/>
          </ns8:apellidos>
        </xsl:if>
        <xsl:if test="/ns1:guardarCompraEntrada/ns1:compra/usuarioEnvio/tipoDocumento">
          <ns8:tipodocumento>
            <xsl:value-of select="/ns1:guardarCompraEntrada/ns1:compra/usuarioEnvio/tipoDocumento"/>
          </ns8:tipodocumento>
        </xsl:if>
        <xsl:if test="/ns1:guardarCompraEntrada/ns1:compra/usuarioEnvio/numeroDocumento">
          <ns8:numerodocumento>
            <xsl:value-of select="/ns1:guardarCompraEntrada/ns1:compra/usuarioEnvio/numeroDocumento"/>
          </ns8:numerodocumento>
        </xsl:if>
        <xsl:if test="/ns1:guardarCompraEntrada/ns1:compra/usuarioEnvio/correoElectronico">
          <ns8:email>
            <xsl:value-of select="/ns1:guardarCompraEntrada/ns1:compra/usuarioEnvio/correoElectronico"/>
          </ns8:email>
        </xsl:if>
        <xsl:if test="/ns1:guardarCompraEntrada/ns1:compra/usuarioEnvio/telefono">
          <ns8:telefono>
            <xsl:value-of select="/ns1:guardarCompraEntrada/ns1:compra/usuarioEnvio/telefono"/>
          </ns8:telefono>
        </xsl:if>
        <xsl:if test="/ns1:guardarCompraEntrada/ns1:compra/usuarioEnvio/direccion/numero">
          <ns8:numerodrirec>
            <xsl:value-of select="/ns1:guardarCompraEntrada/ns1:compra/usuarioEnvio/direccion/numero"/>
          </ns8:numerodrirec>
        </xsl:if>
        <xsl:if test="/ns1:guardarCompraEntrada/ns1:compra/usuarioEnvio/direccion/idCiudad">
          <ns8:idciudad>
            <xsl:value-of select="/ns1:guardarCompraEntrada/ns1:compra/usuarioEnvio/direccion/idCiudad"/>
          </ns8:idciudad>
        </xsl:if>
        <xsl:if test="/ns1:guardarCompraEntrada/ns1:compra/tarjeta/nombreTitular">
          <ns8:titulartarjeta>
            <xsl:value-of select="/ns1:guardarCompraEntrada/ns1:compra/tarjeta/nombreTitular"/>
          </ns8:titulartarjeta>
        </xsl:if>
        <xsl:if test="/ns1:guardarCompraEntrada/ns1:compra/tarjeta/numeroTarjeta">
          <ns8:numerotarjeta>
            <xsl:value-of select="/ns1:guardarCompraEntrada/ns1:compra/tarjeta/numeroTarjeta"/>
          </ns8:numerotarjeta>
        </xsl:if>
      </ns8:Envio>
    </ns8:EnvioCollection>
  </xsl:template>
</xsl:stylesheet>
