<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.kallsony.com/final/operacion/registrarcompra"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.kallsony.com/final/operacion/registrarcompra"
              xmlns:wkrc="http://www.kallsony.com/operacion/registrarcompra"
             xmlns:wkrcf="http://www.kallsony.com/util/falta"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
           >
  <types>
    <xsd:schema targetNamespace="http://www.kallsony.com/final/operacion/registrarcompra"
                elementFormDefault="qualified">
    
      <xsd:import schemaLocation="../xsd/Operacion/RegistrarCompra.xsd"
                  namespace="http://www.kallsony.com/operacion/registrarcompra"/>
      <xsd:import schemaLocation="../xsd/Util/Falta.xsd"
                  namespace="http://www.kallsony.com/util/falta"/>
    </xsd:schema>
  </types>
  
  <message name="Compra_Entrada">
    <part name="partEntrada" element="wkrc:registrarCompraEntrada"/>
  </message>
  <message name="Compra_Salida">
    <part name="partSalida" element="wkrc:registrarCompraSalida"/>
  </message>
  <message name="Compra_Falta">
    <part name="partFalta" element="wkrcf:falta"/>
  </message>
  <portType name="PortCompra">
    <operation name="registrarCompra">
      <input message="tns:Compra_Entrada"/>
      <output message="tns:Compra_Salida"/>
      <fault message="tns:Compra_Falta" name="FaltaCompra"/>
    </operation>
  </portType>
  <binding name="PortCompraSOAP11Binding" type="tns:PortCompra">
    <soap:binding style="document"
                  transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="registrarCompra">
      <soap:operation style="document"
                      soapAction="http://www.kallsony.com/final/operacion/registrarcompra/registrarCompra"/>
      <input>
        <soap:body use="literal" parts="partEntrada"/>
      </input>
      <output>
        <soap:body use="literal" parts="partSalida"/>
      </output>
      <fault name="FaltaCompra">
        <soap:fault name="FaltaCompra" use="literal"/>
      </fault>
    </operation>
  </binding>
  <service name="PortCompra">
    <port name="PortCompraPort" binding="tns:PortCompraSOAP11Binding">
      <soap:address location="http://www.kallsony.com"/>
    </port>
  </service>
</definitions>
