<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.kallsony.com/final/operacion/validartarjeta"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.kallsony.com/final/operacion/validartarjeta"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:wktj="http://www.kallsony.com/operacion/validartarjeta"
             xmlns:wktf="http://www.kallsony.com/util/falta"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema targetNamespace="http://www.kallsony.com/final/operacion/validartarjeta"
                elementFormDefault="qualified">
      <xsd:import schemaLocation="../xsd/Operacion/ValidarTarjeta.xsd"
                  namespace="http://www.kallsony.com/operacion/validartarjeta"/>
      <xsd:import schemaLocation="../xsd/Util/Falta.xsd"
                  namespace="http://www.kallsony.com/util/falta"/>
    </xsd:schema>
  </types>
  <message name="Tarjeta_validarEntrada">
    <part name="partEntrada" element="wktj:validarTarjetaEntrada"/>
  </message>
  <message name="Tarjeta_validarSalida">
    <part name="partSalida" element="wktj:validarTarjetaSalida"/>
  </message>
  <message name="Tarjeta_Falta">
    <part name="partFalta" element="wktf:falta"/>
  </message>
  <portType name="portTarjerta">
    <operation name="validarTarjeta">
      <input message="tns:Tarjeta_validarEntrada"/>
      <output message="tns:Tarjeta_validarSalida"/>
      <fault message="tns:Tarjeta_Falta" name="FaltaTarjeta"/>
    </operation>
  </portType>
  <binding name="portTarjertaSOAP11Binding" type="tns:portTarjerta">
    <soap:binding style="document"
                  transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="validarTarjeta">
      <soap:operation style="document"
                      soapAction="http://www.kallsony.com/final/operacion/validartarjeta/validarTarjeta"/>
      <input>
        <soap:body use="literal" parts="partEntrada"/>
      </input>
      <output>
        <soap:body use="literal" parts="partSalida"/>
      </output>
      <fault name="FaltaTarjeta">
        <soap:fault name="FaltaTarjeta" use="literal"/>
      </fault>
    </operation>
  </binding>
  <service name="portTarjerta">
    <port name="portTarjertaPort" binding="tns:portTarjertaSOAP11Binding">
      <soap:address location="http://www.kallsony.com"/>
    </port>
  </service>
</definitions>
