<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../Compra.wsdl"/>
      <rootElement name="registrarCompraEntrada" namespace="http://www.kallsony.com/operacion/registrarcompra"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="http://DiegoPC:8001/soa-infra/services/default/ProjectTarjeta/Tarjeta.wsdl"/>
      <rootElement name="validarTarjetaEntrada" namespace="http://www.kallsony.com/operacion/validartarjeta"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 140919.1004.0161) AT [WED MAR 25 09:38:15 COT 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:ns6="http://www.kallsony.com/final/operacion/validartarjeta"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns1="http://www.kallsony.com/entidad/compra"
                xmlns:ns3="http://www.kallsony.com/entidad/tarjeta"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:tns="http://www.kallsony.com/final/operacion/registrarcompra"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ns2="http://www.kallsony.com/entidad/producto"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:wkrc="http://www.kallsony.com/operacion/registrarcompra"
                xmlns:wktj="http://www.kallsony.com/operacion/validartarjeta"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns4="http://www.kallsony.com/entidad/orden"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns5="http://www.kallsony.com/entidad/usuario"
                xmlns:wkrcf="http://www.kallsony.com/util/falta"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns0="http://www.kallsony.com/entidad/direccion"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl ns1 ns3 tns soap ns2 wkrc ns4 ns5 wkrcf ns0 xsd ns6 wktj xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <wktj:validarTarjetaEntrada>
      <wktj:tarjeta>
        <xsl:if test="/wkrc:registrarCompraEntrada/wkrc:compra/tarjeta/nombreTitular">
          <nombreTitular>
            <xsl:value-of select="/wkrc:registrarCompraEntrada/wkrc:compra/tarjeta/nombreTitular"/>
          </nombreTitular>
        </xsl:if>
        <xsl:if test="/wkrc:registrarCompraEntrada/wkrc:compra/tarjeta/numeroTarjeta">
          <numeroTarjeta>
            <xsl:value-of select="/wkrc:registrarCompraEntrada/wkrc:compra/tarjeta/numeroTarjeta"/>
          </numeroTarjeta>
        </xsl:if>
        <xsl:if test="/wkrc:registrarCompraEntrada/wkrc:compra/tarjeta/codigoSeguridad">
          <codigoSeguridad>
            <xsl:value-of select="/wkrc:registrarCompraEntrada/wkrc:compra/tarjeta/codigoSeguridad"/>
          </codigoSeguridad>
        </xsl:if>
        <xsl:if test="/wkrc:registrarCompraEntrada/wkrc:compra/tarjeta/fechaExpiracion">
          <fechaExpiracion>
            <xsl:value-of select="/wkrc:registrarCompraEntrada/wkrc:compra/tarjeta/fechaExpiracion"/>
          </fechaExpiracion>
        </xsl:if>
      </wktj:tarjeta>
    </wktj:validarTarjetaEntrada>
  </xsl:template>
</xsl:stylesheet>
