<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="http://DiegoPC:8001/soa-infra/services/default/ProjectTarjeta/Tarjeta.wsdl"/>
      <rootElement name="validarTarjetaSalida" namespace="http://www.kallsony.com/operacion/validartarjeta"/>
    </source>
    <source type="WSDL">
      <schema location="../getPreorden.wsdl"/>
      <rootElement name="getPreordenOutputCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/getPreorden"/>
      <param name="InvokePreOrden_getPreorden_OutputVariable.getPreordenOutputCollection" />
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../Compra.wsdl"/>
      <rootElement name="registrarCompraSalida" namespace="http://www.kallsony.com/operacion/registrarcompra"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 140919.1004.0161) AT [WED MAR 25 10:16:50 COT 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:tns="http://www.kallsony.com/final/operacion/validartarjeta"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns4="http://www.kallsony.com/entidad/compra"
                xmlns:ns0="http://www.kallsony.com/entidad/tarjeta"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:ns2="http://www.kallsony.com/final/operacion/registrarcompra"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns5="http://www.kallsony.com/entidad/producto"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/Appkallsonys/ProjectCompras/getPreorden"
                xmlns:wkrc="http://www.kallsony.com/operacion/registrarcompra"
                xmlns:wktj="http://www.kallsony.com/operacion/validartarjeta"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns6="http://www.kallsony.com/entidad/orden"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns7="http://www.kallsony.com/entidad/usuario"
                xmlns:wktf="http://www.kallsony.com/util/falta"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns3="http://www.kallsony.com/entidad/direccion"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/getPreorden"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl tns ns0 plt soap wsdl ns1 wktj wktf xsd db ns4 ns2 ns5 wkrc ns6 ns7 ns3 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:param name="InvokePreOrden_getPreorden_OutputVariable.getPreordenOutputCollection"/>
  <xsl:template match="/">
    <wkrc:registrarCompraSalida>
      <wkrc:idPreOrden>
        <xsl:value-of select="$InvokePreOrden_getPreorden_OutputVariable.getPreordenOutputCollection/db:getPreordenOutputCollection/db:getPreordenOutput/db:PREORDEN"/>
      </wkrc:idPreOrden>
      <wkrc:estadoTarjeta>
        <xsl:value-of select="/wktj:validarTarjetaSalida/wktj:estado"/>
      </wkrc:estadoTarjeta>
    </wkrc:registrarCompraSalida>
  </xsl:template>
</xsl:stylesheet>
