<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../BPELCancelar.wsdl"/>
      <rootElement name="cancelarEntrada" namespace="http://www.kallsony.com/operacion/cancelarcompra"/>
    </source>
    <source type="WSDL">
      <schema location="../getOrden.wsdl"/>
      <rootElement name="OrdenCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/getOrden"/>
      <param name="InvokeGetOrden_getOrdenSelect_OutputVariable.OrdenCollection" />
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../setCancelacion.wsdl"/>
      <rootElement name="OrdencanceladaCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/setCancelacion"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 140919.1004.0161) AT [TUE JUN 02 19:23:00 COT 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/getOrden"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:ns1="http://www.kallsony.com/operacion/cancelarcompra"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/Appkallsonys/ProjectCancelar/setCancelacion"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Appkallsonys/ProjectCancelar/getOrden"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:client="http://xmlns.oracle.com/Appkallsonys/ProjectCancelar/BPELCancelar"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/top/setCancelacion"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl top ns1 plnk wsdl tns xsd client ns0 ns2 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:param name="InvokeGetOrden_getOrdenSelect_OutputVariable.OrdenCollection"/>
  <xsl:template match="/">
    <ns2:OrdencanceladaCollection>
      <ns2:Ordencancelada>
        <ns2:idorden>
          <xsl:value-of select="$InvokeGetOrden_getOrdenSelect_OutputVariable.OrdenCollection/top:OrdenCollection/top:Orden/top:idorden"/>
        </ns2:idorden>
        <xsl:if test="/ns1:cancelarEntrada/ns1:nombreUsuario">
          <ns2:usuario>
            <xsl:value-of select="/ns1:cancelarEntrada/ns1:nombreUsuario"/>
          </ns2:usuario>
        </xsl:if>
        <xsl:if test="/ns1:cancelarEntrada/ns1:comentario">
          <ns2:comentario>
            <xsl:value-of select="/ns1:cancelarEntrada/ns1:comentario"/>
          </ns2:comentario>
        </xsl:if>
        <ns2:fecha>
          <xsl:value-of select="xp20:current-date()"/>
        </ns2:fecha>
      </ns2:Ordencancelada>
    </ns2:OrdencanceladaCollection>
  </xsl:template>
</xsl:stylesheet>
