<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../Tarjeta.wsdl"/>
      <rootElement name="validarTarjetaEntrada" namespace="http://www.kallsony.com/operacion/validartarjeta"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../getTarjetas.wsdl"/>
      <rootElement name="getTarjetasInput" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/getTarjetas"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 140919.1004.0161) AT [THU MAR 26 11:20:43 COT 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:tns="http://www.kallsony.com/final/operacion/validartarjeta"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns0="http://www.kallsony.com/entidad/tarjeta"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:wktj="http://www.kallsony.com/operacion/validartarjeta"
                xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/getTarjetas"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:wktf="http://www.kallsony.com/util/falta"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/Appkallsonys/ProjectTarjeta/getTarjetas"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl tns ns0 soap wktj wktf xsd plt wsdl db ns1 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <db:getTarjetasInput>
      <db:num_tarjeta>
        <xsl:value-of select="/wktj:validarTarjetaEntrada/wktj:tarjeta/numeroTarjeta"/>
      </db:num_tarjeta>
      <db:mes_exp>
        <xsl:value-of select="xp20:month-from-dateTime(/wktj:validarTarjetaEntrada/wktj:tarjeta/fechaExpiracion)"/>
      </db:mes_exp>
      <db:anio_exp>
        <xsl:value-of select="xp20:year-from-dateTime(/wktj:validarTarjetaEntrada/wktj:tarjeta/fechaExpiracion)"/>
      </db:anio_exp>
      <db:cod_ver>
        <xsl:value-of select="/wktj:validarTarjetaEntrada/wktj:tarjeta/codigoSeguridad"/>
      </db:cod_ver>
    </db:getTarjetasInput>
  </xsl:template>
</xsl:stylesheet>
