<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../Orden.wsdl"/>
      <rootElement name="consultaOrdenEntrada" namespace="http://www.kallsony.com/operacion/consultaorden"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../getOrdenes.wsdl"/>
      <rootElement name="getOrdenesSelect_idPreOrden_estadoOrden_userNameInputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/getOrdenes"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 140919.1004.0161) AT [WED APR 29 11:17:22 COT 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:ns4="http://xmlns.oracle.com/pcbpel/adapter/db/Appkallsonys/ProjectConsultaOrdenes/getOrdenes"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/getOrdenes"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:tns="http://www.kallsony.com/final/operacion/consultaorden"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ns1="http://www.kallsony.com/entidad/producto"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns2="http://www.kallsony.com/entidad/orden"
                xmlns:ns3="http://www.kallsony.com/entidad/usuario"
                xmlns:wkcof="http://www.kallsony.com/util/falta"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns0="http://www.kallsony.com/entidad/direccion"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:wkcor="http://www.kallsony.com/operacion/consultaorden"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl tns soap ns1 ns2 ns3 wkcof ns0 xsd wkcor ns4 top plt wsdl xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <top:getOrdenesSelect_idPreOrden_estadoOrden_userNameInputParameters>
      <xsl:if test="/wkcor:consultaOrdenEntrada/wkcor:idOrden">
        <top:idPreOrden>
          <xsl:value-of select="/wkcor:consultaOrdenEntrada/wkcor:idOrden"/>
        </top:idPreOrden>
      </xsl:if>
      <xsl:if test="/wkcor:consultaOrdenEntrada/wkcor:estadoOrden">
        <top:estadoOrden>
          <xsl:value-of select="/wkcor:consultaOrdenEntrada/wkcor:estadoOrden"/>
        </top:estadoOrden>
      </xsl:if>
      <xsl:if test="/wkcor:consultaOrdenEntrada/wkcor:cliente/nombreUsuario">
        <top:userName>
          <xsl:value-of select="/wkcor:consultaOrdenEntrada/wkcor:cliente/nombreUsuario"/>
        </top:userName>
      </xsl:if>
    </top:getOrdenesSelect_idPreOrden_estadoOrden_userNameInputParameters>
  </xsl:template>
</xsl:stylesheet>
