<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../getOrdenes.wsdl"/>
      <rootElement name="OrdenCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/getOrdenes"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../Orden.wsdl"/>
      <rootElement name="consultaOrdenSalida" namespace="http://www.kallsony.com/operacion/consultaorden"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 140919.1004.0161) AT [WED JUN 03 18:20:19 COT 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Appkallsonys/ProjectConsultaOrdenes/getOrdenes"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/getOrdenes"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns0="http://www.kallsony.com/final/operacion/consultaorden"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ns2="http://www.kallsony.com/entidad/producto"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns3="http://www.kallsony.com/entidad/orden"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns4="http://www.kallsony.com/entidad/usuario"
                xmlns:wkcof="http://www.kallsony.com/util/falta"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns1="http://www.kallsony.com/entidad/direccion"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:wkcor="http://www.kallsony.com/operacion/consultaorden"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl tns top plt wsdl xsd ns0 soap ns2 ns3 ns4 wkcof ns1 wkcor xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <wkcor:consultaOrdenSalida>
      <wkcor:listaOrdenes>
        <xsl:for-each select="/top:OrdenCollection/top:Orden">
          <wkcor:orden>
            <idOrden>
              <xsl:value-of select="top:idorden"/>
            </idOrden>
            <idPreOrden>
              <xsl:value-of select="top:numpreorden"/>
            </idPreOrden>
            <fechaOrden>
              <xsl:value-of select="top:fechaorden"/>
            </fechaOrden>
            <estadoOrden>
              <xsl:value-of select="top:idestadoorden/top:nombreestadoorden"/>
            </estadoOrden>
            <idEstadoOrden>
              <xsl:value-of select="top:idestadoorden/top:idestadoorden"/>
            </idEstadoOrden>
            <numeroItems>
              <xsl:value-of select="top:cantitemorden"/>
            </numeroItems>
            <total>
              <xsl:value-of select="top:totalorden"/>
            </total>
            <listaItems>
              <xsl:for-each select="top:itemOrdenCollection/top:ItemOrden">
                <items>
                  <cantidad>
                    <xsl:value-of select="top:cantidaditem"/>
                  </cantidad>
                  <tipo>
                    <xsl:value-of select="top:tipoitem"/>
                  </tipo>
                  <idCampania>
                    <xsl:value-of select="top:idproducto"/>
                  </idCampania>
                  <producto>
                    <idProducto>
                      <xsl:value-of select="top:idproducto"/>
                    </idProducto>
                    <codigoProducto>
                      <xsl:value-of select="top:codigoproducto"/>
                    </codigoProducto>
                    <nombreProducto>
                      <xsl:value-of select="top:nombreproducto"/>
                    </nombreProducto>
                    <descripcionProducto>
                      <xsl:value-of select="top:nombreproducto"/>
                    </descripcionProducto>
                    <precioProducto>
                      <xsl:value-of select="top:valorunitarioitem"/>
                    </precioProducto>
                  </producto>
                </items>
              </xsl:for-each>
            </listaItems>
          </wkcor:orden>
        </xsl:for-each>
      </wkcor:listaOrdenes>
    </wkcor:consultaOrdenSalida>
  </xsl:template>
</xsl:stylesheet>
