<?binding.jca getUsuario_db.jca?>
<wsdl:definitions name="getUsuario" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Appkallsonys/ProjectGuardarOrden/getUsuario" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Appkallsonys/ProjectGuardarOrden/getUsuario" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/getUsuario">
    <plt:partnerLinkType name="getUsuario_plt">
        <plt:role name="getUsuario_role">
            <plt:portType name="tns:getUsuario_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/getUsuario" schemaLocation="xsd/getUsuario_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="getUsuarioSelect_inputParameters">
        <wsdl:part name="getUsuarioSelect_inputParameters" element="top:getUsuarioSelect_paramUsernameInputParameters"/>
    </wsdl:message>
    <wsdl:message name="UsuarioCollection_msg">
        <wsdl:part name="UsuarioCollection" element="top:UsuarioCollection"/>
    </wsdl:message>
    <wsdl:portType name="getUsuario_ptt">
        <wsdl:operation name="getUsuarioSelect">
            <wsdl:input message="tns:getUsuarioSelect_inputParameters"/>
            <wsdl:output message="tns:UsuarioCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
